### ISSUE TITLE
Push plugin is crashing on Galaxy s3

### ISSUE THREAD

**Issue by atgillette** [phonegap/phonegap-plugin-push#1020]
### Expected Behaviour
To be able to initialize push plugin in app without crashing

### Actual Behaviour
Crashes app during push plugin initialization

### Reproduce Scenario (including but not limited to)
Launch app

#### Steps to Reproduce 
Launch app

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
OS - Android 4.4.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Device - Samsumg Galaxy S3

#### Cordova CLI version and cordova platform version

    cordova --version                                     6.2.0
    cordova platform version android                     5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin- 1.7.1

#### Sample Push Data Payload
none

#### Sample Code that illustrates the problem
```
push = PushNotification.init({
      android: {
        senderID    : 'xxxxxxxx'
      },
      ios: {
        senderID    : 'xxxxxxxxx',
        gcmSandbox  : config.pushNotification[config.selectedEnv],
        alert       : true,
        badge       : true,
        sound       : true
      }
    });
```

#### Logs taken while reproducing problem
```
Fatal Exception: java.lang.IncompatibleClassChangeError: android.support.v4.content.ContextCompat
       at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
       at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
       at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
       at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:75)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

Crashed: pool-1-thread-4: 0 0 0x0000000000000000
       at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
       at com.google.android.gms.iid.zzd.<init>(Unknown Source)
       at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
       at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
       at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:75)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by macdonst** [comment]
Update Google play services on your device and retest. Let me know if that
fixes it.

**Comment by atgillette** [comment]
Thanks for the suggestion.  It's happening on two phones that have older versions of Google Play.  I'll let you know if doing that fixes the issue.

**Comment by sanctus671** [comment]
Having the same issue on Moto G2 Android 6.0. App crashes at launch

**Comment by macdonst** [comment]
@sanctus671 Is it the same stack trace as above?

**Comment by Ele-** [comment]
@macdonst Same issuse Moto G1 Android 6.0 on version 1.7.1 and 1.7.2 of the plugin.
@atgillette @sanctus671 it works with version 1.7.0 of the plugin.

**Comment by atgillette** [comment]
One of the users has Google Play version 6.7.13.E.  He says that's the latest available to his phone.

**Comment by macdonst** [comment]
Everyone this is because of a problem with Google Play Services, seriously Google screwed up and released an incompatible library. You should make sure you are using the latest version of Google Play Services to compile the app and request your users update to the latest possible version as well.

**Comment by marcomow** [comment]
how is possible to update google play service to latest version in Phonegap Build?

**Comment by macdonst** [comment]
@marcomow I asked the PGB team to update the servers.

**Comment by macdonst** [comment]
@atgillette same root cause of #909. You'll need to update your build environment with the latest Google Play Services and make sure your phones are up to date as well.

**Comment by marcomow** [comment]
@macdonst thank you! How can check if pgb has been updated?

**Comment by ezequielnaftali** [comment]
any news on this? how can I check if they updated?

**Comment by cmalard** [comment]
https://twitter.com/phonegapbuild/status/758412620038713345
