### ISSUE TITLE
Help with SenderID

### ISSUE THREAD

**Issue by Giusti** [phonegap/phonegap-plugin-push#1071]
So I am working with telerik Appbuilder Extension for Visual Studio, there I can import the zip plugin, but I cant add the plugin via commandline so I am not able to set the SENDER_ID as described in the Installation guide. My app is not going into the Appstore, so I dont care if there are some restrictions with the SENDER_ID having to be predefined. 

What I tried so far:
I already tried to add the plugin via the cordova commandline, which returns "this is not a cordova based project"
I tried adding the SENDER_ID to the Config.xml like this
```
<plugin name="phonegap-plugin-push" spec="1.6.0">
          <param name="SENDER_ID" value="123456789" />
        </plugin>
```
I also took a look into the plugin to see if I could just hardcode my SenderID somewhere but didnt find anything.

So how can I add my SenderId to get this to work, since I cant event build it because its telling me the variable SENDER_ID is missing...

Regards Chris

**Comment by macdonst** [comment]
@Giusti sorry, I don't have any experience with Telerik's Appbuilder Extension for Visual Studio so I'm not sure how to specify the SENDER_ID parameter. Please ask on the Telerik forums and let me know and I'll add it to the docs.

**Comment by macdonst** [comment]
@Giusti yeah, that Telerik plugin is based off the old plugin source code. You can always hardcode the sender ID but I think you are better off just asking Telerik how to pass variables to the plugin. They are usually quite responsive.

**Comment by gabor82** [comment]
<plugin name="phonegap-plugin-push" version="~1.6.0" src="https://github.com/phonegap/phonegap-plugin-push">
    <param name="SENDER_ID" value="712044987988" />
  </plugin>

**Comment by Giusti** [comment]
Could you tell me where i should hardcode it (file / line) while i am waiting for an answer from telerik

**Comment by Giusti** [comment]
Will do thanks for the help

**Comment by Giusti** [comment]
Sadly Gabor after changing what you posted in my Config it is still not letting me build because of missing Variable SENDER_ID, but for now I am going to Hardcode it until telerik gives me an answer usually takes 3-4 days though... thanks

**Comment by Giusti** [comment]
@macdonst So I did try to hardocde the SENDER_ID as you mentioned but I am still getting the Build error.

PushPlugin.java Line 66 -> senderID = "453......"; instead of senderID = jo.getString(SENDER_ID);

I also tried:

String hardcodedID = "485.........";
senderID = hardcodedID;

Erro:

Warning: Failed to install 'phonegap-plugin-push':Error: Variable(s) missing: SENDER_ID
    at /home/builder/BpcTooling/Cordova3/pm-5.0-/node_modules/cordova-lib/cordova-lib/src/plugman/install.js:346:23
    at _fulfilled (/home/builder/BpcTooling/Cordova3/pm-5.0-/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/builder/BpcTooling/Cordova3/pm-5.0-/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/builder/BpcTooling/Cordova3/pm-5.0-/node_modules/q/q.js:749:13)
    at /home/builder/BpcTooling/Cordova3/pm-5.0-/node_modules/q/q.js:557:44
    at flush (/home/builder/BpcTooling/Cordova3/pm-5.0-/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
	Warning: Variable(s) missing: SENDER_ID
	Warning: /home/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:190
							throw Error("exit code: " + code);
							^

Error: exit code: 1
at Error (native)
    at ChildProcess.<anonymous> (/home/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:190:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	Error: Build failed during execution
	Error: 'Build failed with error code 1'
Done building project "Datakey.tmp.proj" -- FAILED.

**Comment by macdonst** [comment]
@Giusti right, you'd have to remove https://github.com/phonegap/phonegap-plugin-push/blob/master/plugin.xml#L19 as well.

**Comment by Giusti** [comment]
@macdonst Thank you very much now it is working correctly, really appreciate the quick help

**Comment by Giusti** [comment]
@macdonst Sorry to bother again could you link me the Location for the senderID in the iOS file where to put the hardcoded ID I just looked through the PushPlugin.m file I guess somewhere there

**Comment by macdonst** [comment]
@Giusti https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/PushPlugin.m#L297

**Comment by Giusti** [comment]
@macdonst thank you very much really appreciate it

**Comment by Giusti** [comment]
@macdonst Hey I got an answer from Telerik regarding the Installation process and defining the SENDER_ID Variable here is the answer:

To install the phonegap-push-plugin you can consult with this section and follow these steps:

- Download the plugin as a ZIP from GitHub.
- In the Solution Explorer, right-click Plugins and select Import Plugin.
- Navigate to the zipped plugin package and select it.
- In the Solution Explorer, double-click Properties.
- Locate your plugin in the Other Plugins section.
- Click + for the newly added plugin to expand its configuration options.
- Click Configure.
- Select the build configuration to which you want to apply the plugin variables.
- Provide values for the listed variables and click Close.
- Press Ctrl+S to save your changes.
