### ISSUE TITLE
Unable to build Android app in PGB

### ISSUE THREAD

**Issue by mattcollins171** [phonegap/phonegap-plugin-push#1131]
#### Steps to Reproduce 

I'm using PGB to create the apk, and when pulling the latest code from GitHub is comes out with the logs (below) for Android. Works fine with iOS. I would really appreciate some help from anybody who was at the same problem.

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Building for Android

#### Cordova CLI version and cordova platform version

    Phonegap version                                    6.3.0
    Phonegap platform version android           5.2.1

#### Plugin version

    cordova plugin version - 1.8.0, although I've tried it with others and still get the same result

#### Logs taken while reproducing problem

Build logs
Build Date: 2016-07-30 09:30:34 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-statusbar@~2.1.3" via npm
Installing "cordova-plugin-statusbar" at "2.1.3" for android
"plugman install --platform android --project /project --plugin phonegap-plugin-push --var SENDER_ID=924487731713": Fetching plugin "phonegap-plugin-push" via npm
Installing "phonegap-plugin-push" at "1.8.0" for android
Failed to install 'phonegap-plugin-push':Error: Invalid character entity
Line: 3
Column: 35
Char: ;
    at error (/project/cordova/node_modules/sax/lib/sax.js:347:8)
    at strictFail (/project/cordova/node_modules/sax/lib/sax.js:364:22)
    at parseEntity (/project/cordova/node_modules/sax/lib/sax.js:577:5)
    at Object.write (/project/cordova/node_modules/sax/lib/sax.js:980:29)
    at XMLParser.feed (/project/cordova/node_modules/elementtree/lib/parsers/sax.js:48:15)
    at ElementTree.parse (/project/cordova/node_modules/elementtree/lib/elementtree.js:271:10)
    at Object.exports.XML (/project/cordova/node_modules/elementtree/lib/elementtree.js:606:13)
    at Object.module.exports.parseElementtreeSync (/project/cordova/node_modules/cordova-common/src/util/xml-helpers.js:123:38)
    at ConfigFile_load [as load] (/project/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:74:41)
    at new ConfigFile (/project/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:51:10)
Invalid character entity
Line: 3
Column: 35
Char: ;

**Comment by fredgalvao** [comment]
1. Are you able to build your application if you remove/don't add this plugin `phonegap-plugin-push`?
1. Are you able to install any other plugin in your application?

It seems clear to me that the error you're encountering is not related to this plugin at all, but instead a faulty npm dependency installation OR an incorrently formatted config.xml on your project. You could try to reinstall phonegap locally with `npm -g rm phonegap && npm -g i phonegap` and see if it changes anything. Or try to validate your config.xml somewhere, [like here](http://codebeautify.org/xmlvalidator).

**Comment by macdonst** [comment]
@mattcollins171 yeah, I agree with @fredgalvao. The error seems to indicate you have a `;` character on line three of your `config.xml` around the 35th character in that line. 

I'm going to close this issue as I believe it to be a wayward character but please update us with your findings.

**Comment by mattcollins171** [comment]
@fredgalvao & @macdonst, thanks for your help, in the end it what's a loose ; in the end.

**Comment by TwinLight** [comment]
Hello i'm having the same issues here. As @fredgalvao suggests, the error still throw after rm and add this plugin, and xmlValidator no problem.


ionic info:
```
Cordova CLI: 6.4.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
ios-deploy version: Not installed
ios-sim version: 5.0.13
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

Config.xml
```
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.path.appname" version="1.0.3" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Savi</name>
    <author email="app@example.com" href="http://example.com">AppName</author>
    <description>App description</description>
    <content src="index.html" />
    <access origin="*" />
    <preference name="Fullscreen" value="false" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="LoadUrlTimeoutValue" value="70000" />
    <preference name="FadeSplashScreenDuration" value="2000" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="10000" />
    <preference name="FadeSplashScreen" value="true" />
    <feature name="StatusBar">
        <param name="ios-package" onload="true" value="CDVStatusBar" />
    </feature>
    <plugin name="cordova-plugin-console" spec="~1.0.4" />
    <plugin name="cordova-plugin-whitelist" spec="~1.3.0" />
    <plugin name="cordova-plugin-splashscreen" spec="~4.0.0" />
    <plugin name="cordova-plugin-statusbar" spec="~2.2.0" />
    <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git" />
    <plugin name="cordova-plugin-geolocation" spec="~2.4.0" />
    <plugin name="cordova-plugin-network-information" spec="~1.3.0" />
    <plugin name="cordova-plugin-file" spec="~4.3.0" />
    <plugin name="cordova-plugin-nativeaudio" spec="https://github.com/SidneyS/cordova-plugin-nativeaudio.git" />
    <plugin name="cordova-plugin-vibration" spec="~2.1.2" />
    <plugin name="cordova-plugin-cocoapod-support" spec="~1.2.10" />
    <platform name="android">
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
    </platform>
    <icon src="resources/android/icon/drawable-xhdpi-icon.png" />
    <plugin name="phonegap-plugin-push" spec="~1.9.2">
        <variable name="SENDER_ID" value="XXXXXX" />
    </plugin>
</widget>
```

Thanks

**Comment by TwinLight** [comment]
Found out what the error with.  For some reason when i `rm` this plugin `<plugin name="cordova-plugin-cocoapod-support" spec="~1.2.10" />` i'm able to run it again.

**Comment by fredgalvao** [comment]
Cocoapod support is native to cordova since [cordova-ios 4.3.0](https://cordova.apache.org/announcements/2016/10/24/ios-release.html), so you might not need that plugin anymore anyway.
