### ISSUE TITLE
Android DexForDebug - MultipleDex BUG

### ISSUE THREAD

**Issue by Hurinj** [phonegap/phonegap-plugin-push#1209]
I am doing a cordova app. The iOS is running well. But today, I tried it for Android. When I run the command : cordova build android I have the build failed ..

```
:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

BUILD FAILED
```

Total time: 37.222 secs
Error: Error code 1 for command: /Users/guillaume/Desktop/fcm/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/guillaume/Desktop/fcm/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
Before that, there is also that comment :

To run dex in process, the Gradle daemon needs a larger heap.
It currently has approximately 910 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to more than 2048 MB.
To do this set org.gradle.jvmargs=-Xmx2048M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
```

So I tried to add org.gradle.jvmargs=-Xmx2048M in the gradle.properties, but I think this file is only in platform folder, so if I change it, it will stay the same when I will run "cordova build android" again...

In Installlation topic of this plugin, it said I can have error in MultipleDex and ask for an update ?

Do you know what to do ?

**Comment by Hurinj** [comment]
New console error mentionning firebase !

```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;
    	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
    	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
    	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
    	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
    	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    	at com.android.dx.command.dexer.Main.run(Main.java:277)
    	at com.android.dx.command.dexer.Main.main(Main.java:245)
    	at com.android.dx.command.Main.main(Main.java:106)
    
:transformClassesWithDexForDebug FAILED
```
