### ISSUE TITLE
Uncaught (in promise): Error: Push plugin not found! See logs

### ISSUE THREAD

**Issue by MELAS007** [phonegap/phonegap-plugin-push#1406]
i installed phonegap-plugin-push v2.0.x and i use ionic v2.

on ionic serve, it appears this issues:

```
Error: Uncaught (in promise): Error: Push plugin not found! See logs.
    at s (http://localhost:8100/build/polyfills.js:3:8568)
    at s (http://localhost:8100/build/polyfills.js:3:8391)
    at http://localhost:8100/build/polyfills.js:3:8902
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:14051)
    at Object.onInvokeTask (\D:\Mobile_apps\test\pushtest\node_modules\@angular\core\src\zone\ng_zone.js:229:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:13987)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:11411)
    at i (http://localhost:8100/build/polyfills.js:3:8028)
```
and when i do : ionic run android, it doesn't appears any issue but it doesn't work!!!

Any help plz!

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by borodiliz** [comment]
I have solved this problem [thanks to this comment](https://github.com/driftyco/ionic-cloud/issues/106#issuecomment-268045000)
