### ISSUE TITLE
Push Notifications doesn't sent on iOS 10+

### ISSUE THREAD

**Issue by amauryleproux** [phonegap/phonegap-plugin-push#1435]
Hello,

### Expected Behaviour
Notifications sent on every mobiles devices on every iOS.

### Actual Behaviour
Notifications are just send on mobiles devices using iOS < 10 (9 - 8 ect)
When users use iOS 10 or + notifications are create and (I guess) sent because the code is 201 - CREATED.

### Reproduce Scenario (including but not limited to)
Just push notifications from mobile app or website and not receive notificaiton on devices using iOS 10 or +

#### Steps to Reproduce 
Just push notifications from mobile app or website and not receive notificaiton on devices using iOS 10 or +

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10 or + => doesn't work
iOS 9 - 8 => it's work

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
I don't test on android devices

#### Cordova CLI version and cordova platform version

    cordova --version                                    : 6.4.0
    cordova platform version android           : 

Installed platforms:
  android 5.2.2
  ios 4.2.1
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0

#### Plugin version

 phonegap-plugin-push 1.6.0 "PushPlugin"

#### Sample Push Data Payload

var req = {
      method: 'POST',
      url: 'https://api.ionic.io/push/notifications',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ***************************************'
      },
      data: {
        "tokens": [token],//[token],//post.people.socialtoken,
        "profile":"********",
        "notification":
        {
          "message": msg,"badge": 1,
          "ios": {"message": msg,"badge": 1},
          //"ios": {"message": msg,"badge": 1,"payload": {"link": link,"where":where}},
          "android": {"message": msg,"badge": 1,"payload": {"link": link,"where":where}}
        }
      }
    };
    // Make the API call
    $http(req).success(function(resp){
      console.log(resp);
    }).error(function(error){
      // Handle error
      console.log(error);
    });

#### Sample Code that illustrates the problem

var req = {
      method: 'POST',
      url: 'https://api.ionic.io/push/notifications',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ***************************************'
      },
      data: {
        "tokens": [token],//[token],//post.people.socialtoken,
        "profile":"********",
        "notification":
        {
          "message": msg,"badge": 1,
          "ios": {"message": msg,"badge": 1},
          //"ios": {"message": msg,"badge": 1,"payload": {"link": link,"where":where}},
          "android": {"message": msg,"badge": 1,"payload": {"link": link,"where":where}}
        }
      }
    };
    // Make the API call
    $http(req).success(function(resp){
      console.log(resp);
    }).error(function(error){
      // Handle error
      console.log(error);
    });

#### Logs taken while reproducing problem
no logs error

So, first question, do you have any ideas to fix this problem?
Then, how can I update my phonegap plugin?

Thanks

**Comment by jcesarmobile** [comment]
You are using the 1.6.0 version of the plugin which was created long before iOS 10 was announced and released, you should update to latest version (1.9.1) as some changes where made to make push work on iOS 10.

As 1.9.1 requires cordova-ios 4.3.0, cordova-android 6.0.0 and cordova CLI 6.4.0 you should update all of them too.
If you can't update them, you can test with latest version of the plugin compatible with your platforms and CLI, 1.8.4

**Comment by amauryleproux** [comment]
Hi,

Thank you very much,

Can you tell me how can I update phonegap-plugin-push?

Thanks :)

Amaury Leproux
Développement Web - Développement Mobile - Référencement - Community Management

Site web : www.aleproux.com <http://www.aleproux.com/>

**Comment by fredgalvao** [comment]
A possible list of steps to upgrade to 1.8.4 would be:

```
cordova plugin rm phonegap-plugin-push
cordova plugin add --save phonegap-plugin-push@1.8.4 --variable SENDER_ID="XXXXXXX"
```

**Comment by amauryleproux** [comment]
Thanks @fredgalvao, I've just tied that but I got this error message : 

Uninstalling phonegap-plugin-push from android
Error: ENOENT: no such file or directory, open '/Applications/MAMP/htdocs/usmileapp-v2/platforms/android/assets/www/cordova_plugins.js'

**Comment by amauryleproux** [comment]
Thanks I could update phonegap-plugin-push, now I will test this new version.

**Comment by amauryleproux** [comment]
Hi Guys, me again :/

When I try to install phonegap-plugin-push 1.9.1 (cordova plugin add --save phonegap-plugin-push@1.9.1 --variable SENDER_ID="***********") 

I get this error message: 

Failed to install 'phonegap-plugin-push':Error: pod: Command failed with exit code 1 Error output:
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 1085k    0 1085k    0     0  2754k      0 --:--:-- --:--:-- --:--:-- 2950k
   dyld: lazy symbol binding failed: Symbol not found: _ERR_remove_thread_state
     Referenced from: /usr/local/lib/libcurl.4.dylib
     Expected in: flat namespace

   dyld: Symbol not found: _ERR_remove_thread_state
     Referenced from: /usr/local/lib/libcurl.4.dylib
     Expected in: flat namespace
    at ChildProcess.whenDone (/Applications/MAMP/htdocs/usmileapp-v2/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)
Error: pod: Command failed with exit code 1 Error output:
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 1085k    0 1085k    0     0  2754k      0 --:--:-- --:--:-- --:--:-- 2950k
   dyld: lazy symbol binding failed: Symbol not found: _ERR_remove_thread_state
     Referenced from: /usr/local/lib/libcurl.4.dylib
     Expected in: flat namespace

   dyld: Symbol not found: _ERR_remove_thread_state
     Referenced from: /usr/local/lib/libcurl.4.dylib
     Expected in: flat namespace


i alreday try to do : remove this plugin -> pod repo update -> reinstall this plugin but that's not work.


Do you have any ideas please?

Thanks

**Comment by fredgalvao** [comment]
Did you update your platforms to the 1.9.x requirements stated [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PLATFORM_SUPPORT.md)? AFAIK you had 
> android 5.2.2
> ios 4.2.1

 and we need 
> android 6.0.0
> ios 4.3.0

Specifically, pod suport is [available mainly on cordova-ios 4.3.0](https://cordova.apache.org/announcements/2016/10/24/ios-release.html), and also you might want to try `pod repo update` when the plugin is installed, instead of doing it right after the plugin was removed.

**Comment by amauryleproux** [comment]
When i run cordova version platform ios : 
Installed platforms:
  android 6.0.0
  ios 4.3.1

and cordova -v : 6.4.0

**Comment by codeHatcher** [comment]
I would make sure your certificates and everything is working on. I just used pusher to test this found here https://github.com/noodlewerk/NWPusher From there I realized something else was not setup properly but that was what initially led me to fixing a problem I was having with another library (mixpanel integration with push notifications)

**Comment by amauryleproux** [comment]
Hi @codeHatcher and thanks for the reply.

So you think I have a wrong setup?

On iOS 9 and 8 and before it's working properly.

**Comment by amauryleproux** [comment]
I've always the same error message when I try to install phonegap version 1.9.1 : 

Failed to install 'phonegap-plugin-push':Error: pod: Command failed with exit code 1 Error output:
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 1085k    0 1085k    0     0  2103k      0 --:--:-- --:--:-- --:--:-- 2167k
   dyld: lazy symbol binding failed: Symbol not found: _ERR_remove_thread_state
     Referenced from: /usr/local/lib/libcurl.4.dylib
     Expected in: flat namespace

   dyld: Symbol not found: _ERR_remove_thread_state
     Referenced from: /usr/local/lib/libcurl.4.dylib
     Expected in: flat namespace
    at ChildProcess.whenDone (/Applications/MAMP/htdocs/usmileapp-v2/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)


:(

**Comment by vigyanhoon** [comment]
Doesn't work for me too in iOS 10.1.1, but works great in iOS 9.

**Comment by fredgalvao** [comment]
@amauryleproux That smells like a node/cordova/pod bug. Can you try creating a new project and adding the plugin from the start, following the steps on the [docs here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md)?

**Comment by dezudas** [comment]
Not able to receive notification using GCM in IOS [works in Android] 
Cordova:  6.4.0
Cordova IOS: ios 4.3.1
phonegap-plugin-push 1.9.2 "PushPlugin"

Device: Iphone 6S Plus
IOS version: 10.2 

I am able to get notification using NWPusher APN but when I try using GCM it is not working

Logs taken while reproducing problem

2016-12-17 21:38:53.998871 Chordpedia[1815:502181] Apache Cordova native platform version 4.3.1 is starting.
2016-12-17 21:38:53.999478 Chordpedia[1815:502181] Multi-tasking -> Device: YES, App: YES
2016-12-17 21:38:54.039921 Chordpedia[1815:502181] Using UIWebView
2016-12-17 21:38:54.041211 Chordpedia[1815:502181] [CDVTimer][handleopenurl] 0.065982ms
2016-12-17 21:38:54.042379 Chordpedia[1815:502181] Unlimited access to network resources
2016-12-17 21:38:54.042445 Chordpedia[1815:502181] [CDVTimer][intentandnavigationfilter] 1.175046ms
2016-12-17 21:38:54.042536 Chordpedia[1815:502181] [CDVTimer][gesturehandler] 0.050008ms
2016-12-17 21:38:54.059073 Chordpedia[1815:502181] [CDVTimer][splashscreen] 16.489983ms
2016-12-17 21:38:54.065705 Chordpedia[1815:502181] [CDVTimer][statusbar] 6.518960ms
2016-12-17 21:38:54.079125 Chordpedia[1815:502181] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-12-17 21:38:54.081038 Chordpedia[1815:502181] [MC] Filtering mail sheet accounts for bundle ID: com.dez.chordpedia, source account management: 1
2016-12-17 21:38:54.083101 Chordpedia[1815:502181] [MC] Result: YES
2016-12-17 21:38:54.083255 Chordpedia[1815:502181] [MC] Filtering mail sheet accounts for bundle ID: com.dez.chordpedia, source account management: 1
2016-12-17 21:38:54.083721 Chordpedia[1815:502181] [MC] Result: YES
2016-12-17 21:38:54.096186 Chordpedia[1815:502181] [CDVTimer][socialsharing] 30.387044ms
2016-12-17 21:38:54.097318 Chordpedia[1815:502181] [CDVTimer][localnotification] 1.031995ms
2016-12-17 21:38:54.097384 Chordpedia[1815:502181] [CDVTimer][localnotification] 0.010014ms
2016-12-17 21:38:54.097424 Chordpedia[1815:502181] [CDVTimer][TotalPluginStartup] 56.306005ms
2016-12-17 21:38:54.104624 Chordpedia[1815:502181] createNotificationChecker
2016-12-17 21:38:54.104669 Chordpedia[1815:502181] not coldstart
2016-12-17 21:38:54.105830 Chordpedia[1815:502181] active
2016-12-17 21:38:54.106006 Chordpedia[1815:502181] PushPlugin skip clear badge
2016-12-17 21:38:54.211535 Chordpedia[1815:502181] [MC] Reading from public effective user settings.
2016-12-17 21:38:54.296198 Chordpedia[1815:502181] Resetting plugins due to page load.
2016-12-17 21:38:54.565405 Chordpedia[1815:502181] Finished load of: file:///var/containers/Bundle/Application/BFE7AC84-5839-495A-BD0C-609AC258C34A/Chordpedia.app/www/index.html
2016-12-17 21:38:54.735060 Chordpedia[1815:502210] Push Plugin register called
2016-12-17 21:38:54.735146 Chordpedia[1815:502210] PushPlugin.register: setting badge to false
2016-12-17 21:38:54.735165 Chordpedia[1815:502210] PushPlugin.register: clear badge is set to 0
2016-12-17 21:38:54.735177 Chordpedia[1815:502210] PushPlugin.register: better button setup
2016-12-17 21:38:54.735640 Chordpedia[1815:502210] GCM Sender ID XXXXXX
2016-12-17 21:38:54.735732 Chordpedia[1815:502210] Using GCM Notification
2016-12-17 21:38:54.735790 Chordpedia[1815:502210] Using GCM Sandbox
2016-12-17 21:38:54.742486 Chordpedia[1815:502181] Push Plugin register success: <XXXXXX>
2016-12-17 21:38:54.765: GCM | GCM library version 1.1.4
2016-12-17 21:38:54.769: GCM | Invalid key in checkin plist: GMSInstanceIDDeviceDataVersion
2016-12-17 21:38:54.771384 Chordpedia[1815:502181] GCM Registration Token: XXXXXX

**Comment by peterpeterparker** [comment]
Same here. Do work on Android and iOS <= 9.

I tried the NWPusher @codeHatcher suggested. I'm not able neither with that tool to send a push notification to one of my iOS10 devices. Got the error:

    Connecting to APN...  (my.package sandbox)
    Connected  (my.package sandbox)
    Pushing..
    Notification error: APN invalid token

The msg says invalid token but it works with my other iOS 9 device so I quite not understand.

I use the default test payload of the tools, also tried to change it, doesn't helped:

    {"aps":{"alert":"Testing.. (2)","badge":1,"sound":"default"}}

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
