### ISSUE TITLE
Plugin Crashes on Samsung phones.

### ISSUE THREAD

**Issue by naveedahmed1** [phonegap/phonegap-plugin-push#1491]
Hi,

The plugin crashes when a user clicks on the push notification on Samsung devices.

**Device Details - Galaxy S4 (jflte)**

```
Galaxy S4 (jflte)
Manufacturer Samsung 
Android version Android 5.0 
RAM (MB) 2048 
Screen size 1080 × 1920 
Screen density (dpi) 480 
OpenGL ES version 2.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model APQ8064
```

**Crash Details**

```
java.lang.OutOfMemoryError: Failed to allocate a 9437196 byte allocation with 4249672 free bytes and 4MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreateFromParcel(Native Method)
	at android.graphics.Bitmap.access$000(Bitmap.java:37)
	at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1645)
	at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1637)
	at android.widget.RemoteViews$BitmapCache.<init>(RemoteViews.java:1101)
	at android.widget.RemoteViews.<init>(RemoteViews.java:2156)
	at android.widget.RemoteViews.<init>(RemoteViews.java:2148)
	at android.app.Notification$BuilderRemoteViews.<init>(Notification.java:5304)
	at android.app.Notification$BuilderRemoteViews.clone(Notification.java:5316)
	at android.app.Notification$BuilderRemoteViews.clone(Notification.java:5302)
	at android.app.Notification.cloneInto(Notification.java:1657)
	at android.app.Notification.clone(Notification.java:1571)
	at android.app.NotificationManager.notify(NotificationManager.java:174)
	at com.adobe.phonegap.push.GCMIntentService.createNotification(GCMIntentService.java:432)
	at com.adobe.phonegap.push.GCMIntentService.showNotificationIfPossible(GCMIntentService.java:301)
	at com.adobe.phonegap.push.GCMIntentService.onMessageReceived(GCMIntentService.java:99)
	at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

**Device Details - Galaxy Note3 (hlteatt)**
```
Manufacturer Samsung 
Android version Android 4.1 
RAM (MB) 3072 
Screen size 1080 × 1920 
Screen density (dpi) 480 
OpenGL ES version 2.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8974

```
**Crash Details:**
```
java.lang.OutOfMemoryError: Failed to allocate a 9437196 byte allocation with 4245872 free bytes and 4MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreateFromParcel(Native Method)
	at android.graphics.Bitmap.access$000(Bitmap.java:37)
	at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1645)
	at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1637)
	at android.widget.RemoteViews$BitmapCache.<init>(RemoteViews.java:1034)
	at android.widget.RemoteViews.<init>(RemoteViews.java:2089)
	at android.widget.RemoteViews.<init>(RemoteViews.java:2081)
	at android.app.Notification$BuilderRemoteViews.<init>(Notification.java:5304)
	at android.app.Notification$BuilderRemoteViews.clone(Notification.java:5316)
	at android.app.Notification$BuilderRemoteViews.clone(Notification.java:5302)
	at android.app.Notification.cloneInto(Notification.java:1653)
	at android.app.Notification.clone(Notification.java:1571)
	at android.app.NotificationManager.notify(NotificationManager.java:174)
	at com.adobe.phonegap.push.GCMIntentService.createNotification(GCMIntentService.java:432)
	at com.adobe.phonegap.push.GCMIntentService.showNotificationIfPossible(GCMIntentService.java:301)
	at com.adobe.phonegap.push.GCMIntentService.onMessageReceived(GCMIntentService.java:99)
	at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by macdonst** [comment]
@naveedahmed1 well unfortunately there is no way to catch out of memory exceptions in Java so I can't guard against it. What we need to figure out is why your app is using so much memory. What is the size of the image you are sending along with the push payload?

**Comment by naveedahmed1** [comment]
I am not sending any image with push payload. Its a simple text notification with max 150 characters of Title and max 250 characters of body. Can large number of notifications results in such error? Since my app allow users to set the types and frequency of notifications.

**Comment by macdonst** [comment]
@naveedahmed1 how big is your default app icon?

**Comment by naveedahmed1** [comment]
In my app I am specifying in Push init

`icon: "res://icon"`

res folder has different sub folders

```
mipmap-xxxhdpi which has 192x192 14.7kb
mipmap-xxhdpi which has 144x144 10.8kb
mipmap-xhdpi which has 96x96 7.1kb
mipmap-xxhdpi which has 144x144 10.8kb
mipmap-mdpi which has 48x48 3.39kb
mipmap-ldpi which has 36x36 2.64kb
mipmap-hdpi which has 72x72 5.44kb

```

**Comment by macdonst** [comment]
@naveedahmed1 did this ever get resolved for you?

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
