### ISSUE TITLE
install plugin and get error EPERM: operation not permitted on IOS

### ISSUE THREAD

**Issue by jimboidaho** [phonegap/phonegap-plugin-push#1510]
Installing on windows 10 
Cordova version 6.4.0
Android version 6.0.0
IOS version 4.3.1

Android seems to install correctly IOS gives me this error .
Subproject Path: CordovaLib
Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push':Error: EPERM: operation not permitted, open 'd:\projects\cordova\soclink\platforms\ios\Modi2Market.xcodeproj\project.pbxproj'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.write (d:\projects\cordova\soclink\platforms\ios\cordova\lib\projectFile.js:74:16)
    at d:\projects\cordova\soclink\platforms\ios\cordova\node_modules\cordova-common\src\PluginManager.js:120:26
    at _fulfilled (d:\projects\cordova\soclink\platforms\ios\cordova\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (d:\projects\cordova\soclink\platforms\ios\cordova\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (d:\projects\cordova\soclink\platforms\ios\cordova\node_modules\q\q.js:796:13)
    at d:\projects\cordova\soclink\platforms\ios\cordova\node_modules\q\q.js:857:14
    at runSingle (d:\projects\cordova\soclink\platforms\ios\cordova\node_modules\q\q.js:137:13)
Error: EPERM: operation not permitted, open 'd:\projects\cordova\soclink\platforms\ios\Modi2Market.xcodeproj\project.pbxproj'

I was able to edit project.pbxproj with notepad.  I also tried to install using an Administrator command window.

**Comment by jimboidaho** [comment]
update: Just tried to install plugin from my mac (the projects resides on my windows computer) got a different error.  Install command line.
sudo cordova plugin add phonegap-plugin-push --variable SENDER_ID="492682249819"

Here is the error.
Plugin "phonegap-plugin-push" already installed on android.
Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push':Error: EACCES: permission denied, open '/Volumes/soclink/platforms/ios/Modi2Market.xcodeproj/project.pbxproj'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.writeFileSync (fs.js:1222:33)
    at Object.write (/Volumes/soclink/platforms/ios/cordova/lib/projectFile.js:74:16)
    at /Volumes/soclink/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:120:26
    at _fulfilled (/Volumes/soclink/platforms/ios/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Volumes/soclink/platforms/ios/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Volumes/soclink/platforms/ios/cordova/node_modules/q/q.js:796:13)
    at /Volumes/soclink/platforms/ios/cordova/node_modules/q/q.js:857:14
    at runSingle (/Volumes/soclink/platforms/ios/cordova/node_modules/q/q.js:137:13)
    at flush (/Volumes/soclink/platforms/ios/cordova/node_modules/q/q.js:125:13)
Error: EACCES: permission denied, open '/Volumes/soclink/platforms/ios/Modi2Market.xcodeproj/project.pbxproj'

**Comment by macdonst** [comment]
@jimboidaho try:

```
cordova platform remove ios
cordova platform add ios
```

**Comment by jimboidaho** [comment]
Just a followup.  The problem was my mac was blocking folders from being removed when mounted to my windows data drive.  Shutdown the make and was able to get by it.
