### ISSUE TITLE
Unable to install for ios platform

### ISSUE THREAD

**Issue by Nilos** [phonegap/phonegap-plugin-push#1586]
### Expected Behaviour

Enter `cordova plugin add phonegap-plugin-push` when ios platform is installed. Command should work and return with success.

### Actual Behaviour

An error is shown:
```
Failed to install 'phonegap-plugin-push':Error
    at copyNewFile (ios/cordova/lib/plugman/pluginHandlers.js:320:15)
    at installHelper (ios/cordova/lib/plugman/pluginHandlers.js:240:13)
    at install (ios/cordova/lib/plugman/pluginHandlers.js:34:13)
    at ActionStack.process (ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (ios/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (ios/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (ios/cordova/Api.js:235:10)
    at handleInstall (/Users/nilos/.nvm/versions/node/v7.3.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:611:6)
    at /Users/nilos/.nvm/versions/node/v7.3.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:407:28
    at _fulfilled (/Users/nilos/.nvm/versions/node/v7.3.0/lib/node_modules/cordova/node_modules/q/q.js:787:54)
Error: Uh oh!
"ios/appname/Plugins/phonegap-plugin-push/AppDelegate+notification.m" already exists!
```
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Node version: v7.3.0
Cordova version: 6.5.0

#### Cordova CLI version and cordova platform version
Installed platforms:
  android 6.1.2
  ios 4.3.1

#### Plugin version
phonegap-plugin-push 1.9.1 "PushPlugin"

**Comment by worzella** [comment]
I think you need to do a 'rm' operation and then do the add. I ran into this a few times today and that seemed to work.

**Comment by nakulkundaliya** [comment]
i'll face same issue.
found any solution ???

**Comment by macdonst** [comment]
@Nilos try removing and re-adding the ios platform first.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.

**Comment by drazik** [comment]
Hello,

Since nobody replied, I can tell you that I just faced this issue, and `rm -rf platforms/ios/<app name>/Plugins/phonegap-plugin-push` solved the issue for me. Thank you very much @macdonst !

**Comment by bizzareshishir** [comment]
@drazik just 'rm', no need to add the plugin again?
