### ISSUE TITLE
Plugin crashes app when trying to render invalid circle image

### ISSUE THREAD

**Issue by mdoelker** [phonegap/phonegap-plugin-push#1704]
### Expected Behaviour
Show notification without the image, like it does when image style is unset.

### Actual Behaviour
App crashes due to fatal exception.

#### Steps to Reproduce 
1. Open app.
2. Move app to background.
3. Receive notification that sets an invalid (404) image url and sets its style to circle.
4. App crashes (App stopped modal comes up)

This also seems to happen on redirected image URLs (e.g. Gravatar fallback image).

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG Nexus 5X (TestObject.com)

#### Cordova CLI version and cordova platform version
CLI: 6.5.0
Android Platform: 6.1.2

#### Plugin version
1.10.2

#### Sample Push Data Payload
```js
{
  data: {
    notId: 1,
    title: 'Title',
    message: 'Message',
    soundname: 'default',
    image: 'http://www.example.org/invalid-image.png',
    'image-type': 'circle',
    'content-available': true
  }
}
```

##### Without image-type (no crash)
```
12:45:48 W System.err : java.io.FileNotFoundException: http://example.org/invalid-image.png
12:45:48 W System.err : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
12:45:48 W System.err : at com.adobe.phonegap.push.GCMIntentService.getBitmapFromURL(GCMIntentService.java:819)
12:45:48 W System.err : at com.adobe.phonegap.push.GCMIntentService.setNotificationLargeIcon(GCMIntentService.java:737)
12:45:48 W System.err : at com.adobe.phonegap.push.GCMIntentService.createNotification(GCMIntentService.java:408)
12:45:48 W System.err : at com.adobe.phonegap.push.GCMIntentService.showNotificationIfPossible(GCMIntentService.java:309)
12:45:48 W System.err : at com.adobe.phonegap.push.GCMIntentService.onMessageReceived(GCMIntentService.java:106)
12:45:48 W System.err : at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
12:45:48 W System.err : at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source)
12:45:48 W System.err : at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source)
12:45:48 W System.err : at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
12:45:48 W System.err : at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
12:45:48 W System.err : at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12:45:48 W System.err : at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12:45:48 W System.err : at java.lang.Thread.run(Thread.java:761)
```

##### With image-style: circle (crashes app)
```
12:46:29 W System.err : java.io.FileNotFoundException: http://example.org/invalid-image.png
12:46:29 W System.err : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
12:46:29 W System.err : at com.adobe.phonegap.push.GCMIntentService.getBitmapFromURL(GCMIntentService.java:819)
12:46:29 W System.err : at com.adobe.phonegap.push.GCMIntentService.setNotificationLargeIcon(GCMIntentService.java:737)
12:46:29 W System.err : at com.adobe.phonegap.push.GCMIntentService.createNotification(GCMIntentService.java:408)
12:46:29 W System.err : at com.adobe.phonegap.push.GCMIntentService.showNotificationIfPossible(GCMIntentService.java:309)
12:46:29 W System.err : at com.adobe.phonegap.push.GCMIntentService.onMessageReceived(GCMIntentService.java:106)
12:46:29 W System.err : at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
12:46:29 W System.err : at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source)
12:46:29 W System.err : at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source)
12:46:29 W System.err : at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
12:46:29 W System.err : at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
12:46:29 W System.err : at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12:46:29 W System.err : at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12:46:29 W System.err : at java.lang.Thread.run(Thread.java:761)
06:46:29 E AndroidRuntime : FATAL EXCEPTION: AsyncTask #8
12:46:29 E AndroidRuntime : Process: com.anonymized.package, PID: 16788
12:46:29 E AndroidRuntime : java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
12:46:29 E AndroidRuntime : at com.adobe.phonegap.push.GCMIntentService.getCircleBitmap(GCMIntentService.java:709)
12:46:29 E AndroidRuntime : at com.adobe.phonegap.push.GCMIntentService.setNotificationLargeIcon(GCMIntentService.java:741)
12:46:29 E AndroidRuntime : at com.adobe.phonegap.push.GCMIntentService.createNotification(GCMIntentService.java:408)
12:46:29 E AndroidRuntime : at com.adobe.phonegap.push.GCMIntentService.showNotificationIfPossible(GCMIntentService.java:309)
12:46:29 E AndroidRuntime : at com.adobe.phonegap.push.GCMIntentService.onMessageReceived(GCMIntentService.java:106)
12:46:29 E AndroidRuntime : at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
12:46:29 E AndroidRuntime : at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source)
12:46:29 E AndroidRuntime : at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source)
12:46:29 E AndroidRuntime : at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
12:46:29 E AndroidRuntime : at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
12:46:29 E AndroidRuntime : at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12:46:29 E AndroidRuntime : at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12:46:29 E AndroidRuntime : at java.lang.Thread.run(Thread.java:761)
12:46:29 W ActivityManager : Force finishing activity com.anonymized.package/.MainActivity
```

**Comment by macdonst** [comment]
@mdoelker sweet, thanks for finding that and raising the issue. Seems like a good bug for someone to send a PR for.

**Comment by mdoelker** [comment]
Yeah I was looking into it closer in the code and this was indeed a quick fix. So here you go.

**Comment by macdonst** [comment]
@mdoelker cool, I'm on really bad conference wifi so I'll check it later.
