### ISSUE TITLE
Problem with receiving notification when app is built on phonegap - second try

### ISSUE THREAD

**Issue by filippetroviccc** [phonegap/phonegap-plugin-push#1780]
### Expected Behaviour
App should be receiving notification. If app is in the background phone should be alerted and when clicked should open confirmation alert that ask him if he want to open specific page. 
### Actual Behaviour
When app is in background phone is alerted by notification but when clicked it just open app. Everything works fine on phonegap developer app but when i build app and install it on my device this problem accurres.
### Reproduce Scenario (including but not limited to)
Build the app that have 2 ways of receiving notification, one when app is in the background and other when app is open. Build your app and try to send notification when app is open.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.4 and 2 more android devices i dont know exact version of android
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy Ace 4
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

#### Sample Push Data Payload
```
  data: {
        title: 'Badge Test',
        message: 'Badges, we don\'t need no stinking badges',
        alertId: 'AlertId'
        alertName:'Tvoj alert'
    }
```
#### Sample Code that illustrates the problem
```
 push.on('notification', function(data) {
     console.log("notifikacije: "+data.additionalData.alertId);
     var alertId = data.additionalData.alertId;
     if (alertId) {
       navigator.notification.confirm(
           'Da li zelite da pogledate novi oglas sa ' + data.additionalData.alertName + 'alerta?',
           function(buttonIndex) {
             if (buttonIndex === 1) {
               showAlertById(alertId);
             }
           },
          'Novi oglas',
          ['Da','Ne']
        );
     } else {
       navigator.notification.alert(
           data.message,         // message
           null,                 // callback
           data.title,           // title
           'Ok'                  // buttonName
       );
     }
}
```
#### Logs taken while reproducing problem
```
V/Push_Plugin(10689): extrasToJSON: {"message":"Badges, we don't need no stinking badges","additionalData":{"alertId":"59370fcda6f8ed0004165034","alertName":"Tvoj alert","foreground":true,"google.message_id":"0:1497303401450228%34e62519f9fd7ecd","coldstart":false},"title":"Badge Test"}
D/SystemWebChromeClient(10689): file:///android_asset/www/cordova.js: Line 312 : Error in Success callbackId: PushNotification1333552155 : TypeError: Cannot call method 'confirm' of undefined
I/chromium(10689): [INFO:CONSOLE(312)] "Error in Success callbackId: PushNotification1333552155 : TypeError: Cannot call method 'confirm' of undefined", source: file:///android_asset/www/cordova.js (312)
```

**Comment by macdonst** [comment]
@filippetroviccc running `adb logcat | grep Push` when testing would help as we'd have logs to look into.

**Comment by filippetroviccc** [comment]
Thank you Simon for replying, this is log that when i use `adb logcat | FINDSTR Push` because i am using windows . I think would be helpful for you to find what was problem.

```
V/Push_Plugin(10689): extrasToJSON: {"message":"Badges, we don't need no stinking badges","additionalData":{"alertId":"59370fcda6f8ed0004165034","alertName":"Tvoj alert","foreground":true,"google.message_id":"0:1497303401450228%34e62519f9fd7ecd","coldstart":false},"title":"Badge Test"}
D/SystemWebChromeClient(10689): file:///android_asset/www/cordova.js: Line 312 : Error in Success callbackId: PushNotification1333552155 : TypeError: Cannot call method 'confirm' of undefined
I/chromium(10689): [INFO:CONSOLE(312)] "Error in Success callbackId: PushNotification1333552155 : TypeError: Cannot call method 'confirm' of undefined", source: file:///android_asset/www/cordova.js (312)
```

**Comment by macdonst** [comment]
@filippetroviccc yeah, there is your error right there:

```
I/chromium(10689): [INFO:CONSOLE(312)] "Error in Success callbackId: PushNotification1333552155 : TypeError: Cannot call method 'confirm' of undefined", source: file:///android_asset/www/cordova.js (312)
```

You are calling `navigator.notification.confirm` without having **cordova-plugin-dialogs** added as one of your plugins. Run `cordova plugin add cordova-plugin-dialogs` then build/run and re-test and you should no longer get the error in the success callback.

The reason you didn't see this in the PhoneGap Developer app is because it includes that plugin by default.

P.S. This is why I ask people to fill out the full issue template as it is much easier to diagnose issues when I have the information.

**Comment by filippetroviccc** [comment]
@macdonst Sorry for not filling out issue template immediate.

By installing **cordova-plugin-dialogs** new problem occurs, I get build error when I try to build my app.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> You have not accepted the license agreements of the following SDK components:
  [SDK Patch Applier v4, Google Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.278 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> You have not accepted the license agreements of the following SDK components:
  [SDK Patch Applier v4, Google Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

P.S. Do I need to open another issue thread for this?

**Comment by macdonst** [comment]
@filippetroviccc the error is right there:

```
* What went wrong:
A problem occurred configuring root project 'project'.
> You have not accepted the license agreements of the following SDK components:
  [SDK Patch Applier v4, Google Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

Run `android` from the command line and accept the Android SDK license.

**Comment by filippetroviccc** [comment]
@macdonst Everything works fine, thank you  for help I will now close this issue.
