### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by SteveKelseyMocapay** [phonegap/phonegap-plugin-push#186]
Cordova version 5.3.3
Plugman version 1.0.4
Android support library 23.0.1 installed
Get the following error when using cordova plugin add phonegap-plugin-push. Anyone have any advice?

Fetching plugin "phonegap-plugin-push" via npm
Installing "phonegap-plugin-push" for android
Error during processing of action! Attempting to revert...
Failed to install 'phonegap-plugin-push':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at Object.module.exports.framework.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:139:35)
    at installWrapper (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:576:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:363:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at Object.module.exports.framework.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:139:35)
    at installWrapper (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:576:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:363:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49

**Comment by macdonst** [comment]
@SteveKelseyMocapay what version of Node/NPM are you using?

**Comment by SteveKelseyMocapay** [comment]
1.4.28

**Comment by macdonst** [comment]
@SteveKelseyMocapay is is possible for you to update your npm version? That seems to be a super old version of npm.

**Comment by SteveKelseyMocapay** [comment]
I updated npm to the lates version and had the same issue. I then removed the platforms, added the plugin and then re-added the plugin and that worked. This can be marked as done as I have gotten past my issue. Thank you for the help.

**Comment by CookieCookson** [comment]
I had this issue too, fixed it by updating the android platform on my project from 3.6.4 to 4.0.0

**Comment by fredgalvao** [comment]
This is not a plugin error, but a cordova error. +1's are welcome [here](https://issues.apache.org/jira/browse/CB-9270).

**Comment by luisaccedo** [comment]
+1
