### ISSUE TITLE
Unable to Install Push Plugin on iOS

### ISSUE THREAD

**Issue by casper123** [phonegap/phonegap-plugin-push#1927]
I'm installing this push plugin on my iOS project but getting this following error

```
Failed to install 'phonegap-plugin-push': Error: pod: Command failed with exit code 1
             at ChildProcess.whenDone 
        (/Users/abdulwahab/Documents/mobileapps/hcApp/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
             at emitTwo (events.js:125:13)
             at ChildProcess.emit (events.js:213:7)
             at maybeClose (internal/child_process.js:927:16)
             at Socket.stream.socket.on (internal/child_process.js:348:11)
             at emitOne (events.js:115:13)
             at Socket.emit (events.js:210:7)
             at Pipe._handle.close [as _onclose] (net.js:545:12)
        Error: pod: Command failed with exit code 1
```

So far I've tried the following

1. Updated pods
2. Reinstall pods
3. Remove platform then again add platform and install
4. Remove plugin and re add plugin after updating pods
5. Created new project and tried all this but same error

This is my system configuration
```
CocoaPods Version: 1.3.1

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.4.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by casper123** [comment]
Okay I've somehow able to fix this problem. I did the following

1. Reinstalled cocoapods
2. Removed ios platform
3. Added ios platform
4. Reinstalled push plugin
5. Run 'pod setup'
6. Run 'pod repo update'
5. Again reinstalled plugin
6. Run command 'ionic cordova build ios'
