### ISSUE TITLE
iOS Action button is not showing - looks similar to issue 1954 recently reported

### ISSUE THREAD

**Issue by stib** [phonegap/phonegap-plugin-push#1961]
### Expected Behaviour
iOS Action buttons should show

### Actual Behaviour
The action buttons are not showing. The message comes through but the Action buttons don't show.

### Reproduce Scenario (including but not limited to)
Initialization code
```
		pushN = PushNotification.init({
		   "android": {
		       "senderID": <my senderID>
		   },
		   "ios": {
		       "senderID": <my senderID>, 
		       "gcmSandbox": true,
		       "sound": "true",
		       "vibration": "true",
		       "badge": "true",
		       "categories": {
		           "invite": {
		               "yes": {
		                   "callback": "app.accept",
		                   "title": "Accept",
		                   "foreground": true,
		                   "destructive": false
		               },
		               "no": {
		                   "callback": "app.reject",
		                   "title": "Reject",
		                   "foreground": true,
		                   "destructive": false
		               },
		               "maybe": {
		                   "callback": "app.maybe",
		                   "title": "Maybe",
		                   "foreground": true,
		                   "destructive": false
		               }
		           },
		           "delete": {
		               "yes": {
		                   "callback": "app.doDelete",
		                   "title": "Delete",
		                   "foreground": true,
		                   "destructive": true
		               },
		               "no": {
		                   "callback": "app.cancel",
		                   "title": "Cancel",
		                   "foreground": true,
		                   "destructive": false
		               }
		           }
		       }
		   },
		   "windows": {}
		});
```

Code to send the notification
```
var apiKey = "<mykey>"
var gcm = require('node-gcm');
var service = new gcm.Sender(apiKey);

var deviceID = "<my device regid>";
var message = new gcm.Message();
message.addNotification({
    	"title": "AUX Scrum new",
    	"body": "Scrum: Daily touchbase @ 10am Please be on time so we can cover everything on the agenda.",
        "click-action": "delete",
    	"notId": "1"
});

service.send(message, { registrationTokens: [ deviceID ] }, function(err, response){
  if (err) {
    console.log(err);
    console.log("Something has gone wrong!");
  } else {
    console.log("Successfully sent with response: ", response);
  }
});
```

When run I get a success message printed out and the notification shows on iOS device - but without the action buttons.

#### Steps to Reproduce 
Code above

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS: 10.2.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A
#### Cordova CLI version and cordova platform version

    cordova --version                                    6.4.0
    cordova platform version android    
       
Installed platforms:
  android 6.0.0
  ios 4.3.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push    1.10.5

#### Sample Push Data Payload
Sample example above

#### Sample Code that illustrates the problem
Code above
#### Logs taken while reproducing problem
Don't see any relevant logs in XCode  (8.2.1) - running app on iOS through XCode

I am trying to follow the example as closely as possible for the Action buttons to show up on iOS but seems like I may be missing something simple.

I don't yet have all the callback functions in place - assuming that shouldn't be a problem as it will be needed when a action button us clicked. To rule it out I tried initializing with just the "delete" category and added the two needed function.

Thank you for your help and pointers.

-S

**Comment by stib** [comment]
Running the code on iPhone 6+ simulator I was able to capture the logs below - as expected ultimately push init fails because notification doesn't work on simulator though the categories seem to get setup ok. For some reason when I point Xcode to my physical device I don't get these logs though the App works fine otherwise.

2017-09-15 07:21:06.243 GroupTrac[42124:4070114] PushPlugin.register: setting badge to false
2017-09-15 07:21:06.243 GroupTrac[42124:4070114] PushPlugin.register: clear badge is set to 0
2017-09-15 07:21:06.244 GroupTrac[42124:4070114] PushPlugin.register: better button setup
2017-09-15 07:21:06.244 GroupTrac[42124:4070114] categories: key delete
2017-09-15 07:21:06.246 GroupTrac[42124:4070114] Adding category delete
2017-09-15 07:21:06.247 GroupTrac[42124:4070114] categories: key invite
2017-09-15 07:21:06.248 GroupTrac[42124:4070114] Adding category invite
2017-09-15 07:21:06.262 GroupTrac[42124:4070114] GCM Sender ID <my sender Id>
2017-09-15 07:21:06.262 GroupTrac[42124:4070114] Using GCM Notification
2017-09-15 07:21:06.263 GroupTrac[42124:4070114] Using GCM Sandbox
2017-09-15 07:21:06.448 GroupTrac[42124:4066362] Push Plugin register failed
2017-09-15 07:21:06.667 GroupTrac[42124:4066362] push error =  - remote notifications are not supported in the simulator
2017-09-15 07:21:06.783 GroupTrac[42124:4066362] ERROR: initPushNotification - Error initializing pushNotificationService - error =  Error:  - remote notifications are not supported in the simulator

**Comment by stib** [comment]
I am not sure if updating this issue's title to reflect similar issues with Android as well is the right Forum etiquette here - please let me know and I will update the title or open another ticket as appropriate.

I copied the code from documentation almost verbatim for Android (captured below). Icon missing errors are understandable (I also tried without icons in the message and get same results) but I get other strange errors about expecting String but getting android.text.SpannableString. **Though the message does show up on my device but without the Action buttons**.

The device is an old Nexus 2 device with Android 4.4.2. Is that an issue?

```
var FCM = require('fcm-node');
var apiKey = "My Api key";
var deviceID = "My device id";
var fcm = new FCM(apiKey);

var message = {
    to: deviceID,
    data: {
        title: "Android only - 2",
        message: "Android message",
        actions: [
            { icon: "emailGuests", title: "EMAIL GUESTS", callback: "app.emailGuests", foreground: true},
            { icon: "snooze", title: "SNOOZE", callback: "app.snooze", foreground: false},
        ]
    }
};

fcm.send(message, function(err, response){
  if (err) {
    console.log(err);
    console.log("Something has gone wrong!");
  } else {
    console.log("Successfully sent with response: ", response);
  }
});

```
Output from adb logcat

```
D/Push_GCMIntentService(23307): onMessage - from: XXXXXXX
D/Push_GCMIntentService(23307): normalize extras
D/Push_GCMIntentService(23307): key = google.sent_time
D/Push_GCMIntentService(23307): replace key google.sent_time with google.sent_time
D/Push_GCMIntentService(23307): key = actions
D/Push_GCMIntentService(23307): replace key actions with actions
D/Push_GCMIntentService(23307): key = title
D/Push_GCMIntentService(23307): replace key title with title
D/Push_GCMIntentService(23307): no locale found for key = title, error Value Android of type java.lang.String cannot be converted to JSONObject
D/Push_GCMIntentService(23307): key = google.message_id
D/Push_GCMIntentService(23307): replace key google.message_id with google.message_id
D/Push_GCMIntentService(23307): key = message
D/Push_GCMIntentService(23307): replace key message with message
D/Push_GCMIntentService(23307): no locale found for key = message, error Value Android of type java.lang.String cannot be converted to JSONObject
D/Push_GCMIntentService(23307): background
D/Push_GCMIntentService(23307): message =[Android message]
D/Push_GCMIntentService(23307): title =[Android only - 2]
D/Push_GCMIntentService(23307): contentAvailable =[null]
D/Push_GCMIntentService(23307): forceStart =[null]
D/Push_GCMIntentService(23307): create notification
E/Push_GCMIntentService(23307): Number format exception - Error parsing notId: Invalid int: "null"
D/Push_GCMIntentService(23307): stored icon=null
D/Push_GCMIntentService(23307): stored iconColor=null
D/Push_GCMIntentService(23307): stored sound=true
D/Push_GCMIntentService(23307): stored vibrate=true
D/Push_GCMIntentService(23307): no icon resource found - using application icon
D/Push_GCMIntentService(23307): create actions: with in-line
D/Push_GCMIntentService(23307): adding action
D/Push_GCMIntentService(23307): adding callback = app.emailGuests
D/Push_GCMIntentService(23307): adding action
D/Push_GCMIntentService(23307): adding callback = app.snooze
W/Bundle  ( 1071): Key android.title expected String but value was a android.text.SpannableString.  The default value <null> was returned.
W/Bundle  ( 1071): Attempt to cast generated internal exception:
W/Bundle  ( 1071): java.lang.ClassCastException: android.text.SpannableString cannot be cast to java.lang.String
W/Bundle  ( 1071): 	at android.os.Bundle.getString(Bundle.java:1121)
W/Bundle  ( 1071): 	at com.getpebble.android.notifications.model.apps.NotificationExtractor.extractContent(NotificationExtractor.java:85)
W/Bundle  ( 1071): 	at com.getpebble.android.notifications.model.apps.NotificationExtractor.extractNotificationContent(NotificationExtractor.java:53)
W/Bundle  ( 1071): 	at com.getpebble.android.notifications.model.PblNotification.<init>(PblNotification.java:140)
W/Bundle  ( 1071): 	at com.getpebble.android.notifications.model.PblNotification.from(PblNotification.java:79)
W/Bundle  ( 1071): 	at com.getpebble.android.notifications.PblNotificationService$1.run(PblNotificationService.java:80)
W/Bundle  ( 1071): 	at com.getpebble.android.common.core.util.ProcessUtil.runWithClearedIdentity(ProcessUtil.java:83)
W/Bundle  ( 1071): 	at com.getpebble.android.notifications.PblNotificationService.onNotificationPosted(PblNotificationService.java:77)
W/Bundle  ( 1071): 	at android.service.notification.NotificationListenerService$INotificationListenerWrapper.onNotificationPosted(NotificationListenerService.java:168)
W/Bundle  ( 1071): 	at android.service.notification.INotificationListener$Stub.onTransact(INotificationListener.java:56)
W/Bundle  ( 1071): 	at android.os.Binder.execTransact(Binder.java:404)
W/Bundle  ( 1071): 	at dalvik.system.NativeStart.run(Native Method)
I/MediaFocusControl(  583):  AudioFocus  requestAudioFocus() from android.media.AudioManager@420fa5e0
D/audio_hw_primary(  177): select_devices: out_snd_device(2: speaker) in_snd_device(0: )
D/ACDB-LOADER(  177): ACDB -> send_afe_cal
E/MediaPlayer(  675): Should have subtitle controller already set
D/dalvikvm( 1071): GC_CONCURRENT freed 5021K, 39% free 11063K/18096K, paused 3ms+8ms, total 64ms
D/dalvikvm( 1071): WAIT_FOR_CONCURRENT_GC blocked 46ms
D/dalvikvm( 1071): WAIT_FOR_CONCURRENT_GC blocked 46ms
D/dalvikvm( 1071): GC_CONCURRENT freed 490K, 38% free 11288K/18096K, paused 2ms+2ms, total 26ms
D/dalvikvm( 1071): WAIT_FOR_CONCURRENT_GC blocked 21ms
D/ConnectivityService(  583): handleInetConditionHoldEnd: net=1, condition=100, published condition=100
I/MediaFocusControl(  583):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@420fa5e0
I/PowerManagerService(  583): Going to sleep by user request...
D/SurfaceFlinger(  174): Screen released, type=0 flinger=0xb8a67450
D/SurfaceControl(  583): Excessive delay in blankDisplay() while turning screen off: 185ms
E/ANDR-PERF-LOCK(  185): Failed to apply optimization for resource: 4 level: 0
V/KeyguardHostView(  675): Initial transport state: 0, pbstate=0
E/com.facebook.katana:SignatureAuthSecureIntent( 1630): Invalid auth bundle
D/dalvikvm(  675): GC_FOR_ALLOC freed 1957K, 22% free 23776K/30456K, paused 43ms, total 43ms
D/dalvikvm(  675): GC_FOR_ALLOC freed 1311K, 26% free 22756K/30456K, paused 27ms, total 27ms
V/KeyguardHostView(  675): hide transport, gen:67
V/KeyguardHostView(  675): music state changed: 0
W/View    (  675): requestLayout() improperly called by android.widget.TextView{426609c0 V.ED.... ......ID 0,0-88,42 #7f0b018b app:id/widget_folder} during layout: running second layout pass
W/View    (  675): requestLayout() improperly called by android.widget.TextView{420ce100 V.ED.... ......ID 0,0-259,33 #7f0b018e app:id/widget_account} during layout: running second layout pass
W/View    (  675): requestLayout() improperly called by android.widget.TextClock{424d9a30 V.ED.... ......ID 163,0-473,213 #7f0e0045 app:id/the_clock} during layout: running second layout pass
W/View    (  675): requestLayout() improperly called by android.widget.TextClock{42588f30 V.ED.... ......ID 206,0-429,38 #7f0e0041 app:id/date} during layout: running second layout pass
D/PhoneStatusBar(  675): disable: < EXPAND* icons alerts TICKER* system_info back home RECENT* clock search >
V/PanelView(  675): animationTick called with dtms=0; nothing to do (h=1184.0 v=-4000.0)
V/PanelView(  675): animationTick called with dtms=0; nothing to do (h=1184.0 v=-4000.0)
V/PanelView(  675): animationTick called with dtms=-5; nothing to do (h=1184.0 v=-4000.0)
D/dalvikvm( 2297): GC_CONCURRENT freed 541K, 6% free 10287K/10928K, paused 3ms+3ms, total 39ms
D/dalvikvm( 1627): GC_CONCURRENT freed 395K, 5% free 9132K/9560K, paused 2ms+2ms, total 29ms
D/BluetoothAdapter(  814): 1107246736: getState() :  mService = null. Returning STATE_OFF
D/PhoneStatusBar(  675): disable: < EXPAND icons alerts TICKER system_info BACK* HOME* RECENT CLOCK* search >
```
Thank you for any feedback/pointers.
-S

**Comment by stib** [comment]
Since the android.text.SpannableString seemed to be caused by the Pebble App on the device I removed the App and that error went away. The new adb logcat output is included below.

```
D/Push_GCMIntentService(23307): onMessage - from: XXXXXX
D/Push_GCMIntentService(23307): normalize extras
D/Push_GCMIntentService(23307): key = google.sent_time
D/Push_GCMIntentService(23307): replace key google.sent_time with google.sent_time
D/Push_GCMIntentService(23307): key = actions
D/Push_GCMIntentService(23307): replace key actions with actions
D/Push_GCMIntentService(23307): key = title
D/Push_GCMIntentService(23307): replace key title with title
D/Push_GCMIntentService(23307): no locale found for key = title, error Value Android of type java.lang.String cannot be converted to JSONObject
D/Push_GCMIntentService(23307): key = google.message_id
D/Push_GCMIntentService(23307): replace key google.message_id with google.message_id
D/Push_GCMIntentService(23307): key = message
D/Push_GCMIntentService(23307): replace key message with message
D/Push_GCMIntentService(23307): no locale found for key = message, error Value Android of type java.lang.String cannot be converted to JSONObject
D/Push_GCMIntentService(23307): background
D/Push_GCMIntentService(23307): message =[Android message]
D/Push_GCMIntentService(23307): title =[Android only - 4]
D/Push_GCMIntentService(23307): contentAvailable =[null]
D/Push_GCMIntentService(23307): forceStart =[null]
D/Push_GCMIntentService(23307): create notification
E/Push_GCMIntentService(23307): Number format exception - Error parsing notId: Invalid int: "null"
D/Push_GCMIntentService(23307): stored icon=null
D/Push_GCMIntentService(23307): stored iconColor=null
D/Push_GCMIntentService(23307): stored sound=true
D/Push_GCMIntentService(23307): stored vibrate=true
D/Push_GCMIntentService(23307): no icon resource found - using application icon
D/Push_GCMIntentService(23307): create actions: with in-line
D/Push_GCMIntentService(23307): adding action
D/Push_GCMIntentService(23307): adding callback = app.emailGuests
D/Push_GCMIntentService(23307): adding action
D/Push_GCMIntentService(23307): adding callback = app.snooze
I/MediaFocusControl(  583):  AudioFocus  requestAudioFocus() from android.media.AudioManager@42298578
V/KeyguardHostView(  675): hide transport, gen:68
E/MediaPlayer(  675): Should have subtitle controller already set
E/AudioSink(  177): received unknown event type: 1 inside CallbackWrapper !
D/audio_hw_primary(  177): select_devices: out_snd_device(2: speaker) in_snd_device(0: )
D/ACDB-LOADER(  177): ACDB -> send_afe_cal
D/ConnectivityService(  583): handleInetConditionHoldEnd: net=1, condition=100, published condition=100
I/MediaFocusControl(  583):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@42298578
V/KeyguardHostView(  675): hide transport, gen:69
W/MessageQueue(  675): Handler (android.media.MediaPlayer$EventHandler) {42699588} sending message to a Handler on a dead thread
W/MessageQueue(  675): java.lang.RuntimeException: Handler (android.media.MediaPlayer$EventHandler) {42699588} sending message to a Handler on a dead thread
W/MessageQueue(  675): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
W/MessageQueue(  675): 	at android.os.Handler.enqueueMessage(Handler.java:626)
W/MessageQueue(  675): 	at android.os.Handler.sendMessageAtTime(Handler.java:595)
W/MessageQueue(  675): 	at android.os.Handler.sendMessageDelayed(Handler.java:566)
W/MessageQueue(  675): 	at android.os.Handler.sendMessage(Handler.java:503)
W/MessageQueue(  675): 	at android.media.MediaPlayer.postEventFromNative(MediaPlayer.java:2335)
W/MessageQueue(  675): 	at dalvik.system.NativeStart.run(Native Method)
V/KeyguardServiceDelegate(  583): onScreenTurnedOn(showListener = com.android.internal.policy.impl.PhoneWindowManager$17@42a86720)
I/PowerManagerService(  583): Waking up from sleep...
E/com.facebook.katana:SignatureAuthSecureIntent( 1630): Invalid auth bundle
E/ANDR-PERF-LOCK(  185): Failed to reset optimization for resource: 4 level: 0
D/SurfaceFlinger(  174): Screen acquired, type=0 flinger=0xb8a67450
```

**Comment by stib** [comment]
After more experimenting, I tried a slightly newer Android device, I noticed that the buttons show up but then they hide soon after. Then I went back to the messages on the older Android Nexus 2 device and I found that if I tried to slide the message down then the action buttons show up. Not sure why they are hidden and if there is a way to force them to show all the time but at least the mystery of buttons not showing on Android is solved.

However I am still stuck on buttons not showing on ios devices though the notification message is showing. Tried using the same trick as in older Android device but you can't slide open the buttons on ios. Feels like I must be missing something obvious as it looks fairly straightforward in the examples and the notification message is showing, just the buttons are not. Appreciate any pointers experts on this forum may have to test/debug/resolve this issue for ios.

Thanks,
-S

**Comment by macdonst** [comment]
@stib that is normal behaviour on Android phones. On your iOS devices did you try sliding the notification to the left to reveal the buttons?

**Comment by stib** [comment]
Thank you @macdonst - I did try that and I see buttons View and Clear which seems to be standard for all messages. It doesn't show my buttons Delete and Cancel in the example above.

**Comment by stib** [comment]
Thanks @macdonst  I figured it out. You have to tap on the View button for the Action buttons to show up - I thought from the documentation that the Action buttons will show with the message as they do in Android. So that mystery is solved.

Is there anyway for the buttons to show up inline with the message on iOS as in Android?

Also, it sounds like we will need to send separate messages to Android and iOS devices when you need Action Buttons. Is that correct? Is there a way to combine them in one GCM message? Perhaps I should open another thread for this.

**Comment by macdonst** [comment]
@stib nope, they will show up when the notification is initially shown but then they'll recede to save space. Sorry, you'll need to send one payload for ios and a second payload for android.

**Comment by stib** [comment]
Thanks @macdonst - appreciate the clarification.

**Comment by Rvpsl** [comment]
We are working on IONIC1 app and using FCM server for Android Notification and APNS for iOS notification.

Below are the details for notification plugin using for this app.

phonegap-plugin-push version 2.1.2 
fcm version 11.0.1
cordova-plugin-fcm version 2.1.2

we need to show notification with actionable button.(See attached screenshots)
We are using fcm-node and sending the below JSON:

 
{
    "registration_ids": ["my device id"],
    "data": {
        "title": "AUX Scrum",
         "message": "Scrum: Daily touchbase @ 10am Please be on time so we can cover everything on the agenda.",
        "actions": [
             { "icon": "emailGuests", "title": "EMAIL GUESTS", "callback": "emailGuests", "foreground": true},
                { "icon": "snooze", "title": "SNOOZE", "callback": "snooze", "foreground": false}
         ]
    }
}

 

But actions button are not displaying, only default notification is showing.
below link for reference:
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons
