### ISSUE TITLE
Error when try to subscribe a topic 'Invalid appInstanceToken'

### ISSUE THREAD

**Issue by diego-amplya** [phonegap/phonegap-plugin-push#1979]
### Expected Behaviour
Create and register a topic and shows the name of topic on a <p> element.
### Actual Behaviour
Application (debugging on Android) has stopped.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
**Android 4.1.2**
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
**Samsung Galaxy S2 (GT-I9100)**
#### Cordova CLI version and cordova platform version
    cordova --version                                    # e.g. 6.0.0
    **7.0.1**
#### Plugin version
   cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
   **1.8.0**
#### Sample Code that illustrates the problem
In my index.js:

`var topic = "topictest";
        push.subscribe(topic, function () {
            document.getElementById("topic").innerHTML = topic;
        }, function (e) {
            document.getElementById("topic").innerHTML = "Unable to subscribe topic: " + topic ;
        });
`
#### Logs taken while reproducing problem
I've exported the Phonegap project to an Android project (through 'phonegap build android' command) and import the project on Android Studio) and see the output's on the PushPlugin.java and here it's the output:

 E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
                                                                           java.lang.IllegalArgumentException: Invalid appInstanceToken: 
                                                                               at com.google.android.gms.gcm.GcmPubSub.subscribe(Unknown Source)
                                                                               at com.adobe.phonegap.push.PushPlugin.subscribeToTopic(PushPlugin.java:361)
                                                                               at com.adobe.phonegap.push.PushPlugin.access$700(PushPlugin.java:30)
                                                                               at com.adobe.phonegap.push.PushPlugin$6.run(PushPlugin.java:223)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                               at java.lang.Thread.run(Thread.java:856)

I also print the 'registration_id' variable and it's empty, why?

**Comment by macdonst** [comment]
@diego-amplya sorry, we are only supporting Android 4.4 and higher. I don't have a device capable of running that version of Android anymore. There is a good chance you are not able to register with GCM at all.
