### ISSUE TITLE
Ionic pro Build error

### ISSUE THREAD

**Issue by smasherprog** [phonegap/phonegap-plugin-push#2104]
### Expected Behaviour
Successful build 
### Actual Behaviour
Fails
#### Cordova CLI version and cordova platform version
Not sure, the latest maybe
#### Plugin version

 2.1.2

#### Logs taken while reproducing problem

[00:41:36]: ▸ Discovered plugin "phonegap-plugin-push" in config.xml. Adding it to the project
[00:41:52]: ▸ Installing "phonegap-plugin-push" for ios
[00:41:53]: ▸ Failed to install 'phonegap-plugin-push': undefined
[00:41:53]: ▸ Failed to restore plugin "phonegap-plugin-push" from config.xml. You might need to try adding it again. Error: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'minitest' (~> 5.1) among 31 total gem(s) (Gem::LoadError)
[00:41:53]: ▸ Checked in 'GEM_PATH=/Users/ionic/.fastlane/bin/bundle/bin:/usr/local/Cellar/cocoapods/1.3.1/libexec', execute `gem env` for more information

Does the above error logs mean anything? I am trying to build the ios app in the ionic pro native build process, but it fails. I know you wont debug their problems, but does the log above show what could be the problem?

**Comment by macdonst** [comment]
@smasherprog it really looks like a problem with cocoapods as it is running into an issue with installing the FCM Cocoapod.

**Comment by aelx311** [comment]
I am having the same issue as well. Will downgrading to < 2.1.2 work?

**Comment by smasherprog** [comment]
Thanks for the response. I am trying to downgrade now to see if that helps

**Comment by macdonst** [comment]
@smasherprog it's not the plugin, it's your cocoapods/ruby installation

**Comment by smasherprog** [comment]
I figured .. ill close this as I dont believe this is your problem, but I figured I'd ask.
Thanks for the info

**Comment by macdonst** [comment]
If you can post what was wrong here it might help the next person.

**Comment by aelx311** [comment]
@smasherprog It would be awesome if you could share the solution. Thanks.

**Comment by smasherprog** [comment]
I didnt find a solution. I put in a ticket with ionic as I believe their build image/script is not correct.

**Comment by smasherprog** [comment]
The problem is building an ionic 3 app using the Pro build services. It generates an error when building for versions of this plugin 2.0.0  - 2.1.2
Below is a snippet of the error the build server gives me 

[04:57:29]: ▸ Adding cordova-plugin-badge to package.json
[04:57:29]: ▸ Saved plugin info for "cordova-plugin-badge" to config.xml
[04:57:30]: ▸ Discovered plugin "cordova-plugin-file-transfer" in config.xml. Adding it to the project
[04:57:46]: ▸ Installing "cordova-plugin-file-transfer" for ios
[04:57:47]: ▸ Plugin dependency "cordova-plugin-file@5.0.0" already fetched, using that version.
[04:57:47]: ▸ Dependent plugin "cordova-plugin-file" already installed on ios.
[04:57:47]: ▸ Adding cordova-plugin-file-transfer to package.json
[04:57:47]: ▸ Saved plugin info for "cordova-plugin-file-transfer" to config.xml
[04:57:47]: ▸ Discovered plugin "cordova-plugin-network-information" in config.xml. Adding it to the project
[04:58:05]: ▸ Installing "cordova-plugin-network-information" for ios
[04:58:05]: ▸ Adding cordova-plugin-network-information to package.json
[04:58:05]: ▸ Saved plugin info for "cordova-plugin-network-information" to config.xml
[04:58:05]: ▸ Discovered plugin "phonegap-plugin-push" in config.xml. Adding it to the project
[04:58:23]: ▸ Installing "phonegap-plugin-push" for ios
[04:58:24]: ▸ Failed to install 'phonegap-plugin-push': undefined
[04:58:24]: ▸ Failed to restore plugin "phonegap-plugin-push" from config.xml. You might need to try adding it again. Error: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'minitest' (~> 5.1) among 31 total gem(s) (Gem::LoadError)
[04:58:24]: ▸ Checked in 'GEM_PATH=/Users/ionic/.fastlane/bin/bundle/bin:/usr/local/Cellar/cocoapods/1.3.1/libexec', execute `gem env` for more information
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1439:in `block in activate_dependencies'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `each'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `each'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `each'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
[04:58:24]: ▸ from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
[04:58:24]: ▸ from /usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/bin/pod:36:in `'
[04:58:24]: ▸ from /usr/local/Cellar/cocoapods/1.3.1/libexec/bin/pod:22:in `load'
[04:58:24]: ▸ from /usr/local/Cellar/cocoapods/1.3.1/libexec/bin/pod:22:in `
'
[04:58:24]: ▸ Discovered plugin "cordova-sqlite-storage" in config.xml. Adding it to the project
[04:58:42]: ▸ Installing "cordova-sqlite-storage" for ios
[04:58:42]: ▸ installing external dependencies via npm
[04:58:45]: ▸ npm install of external dependencies ok
[04:58:45]: ▸ Adding cordova-sqlite-storage to package.json
[04:58:45]: ▸ Saved plugin info for "cordova-sqlite-storage" to config.xml
[04:58:45]: ▸ Discovered plugin "cordova-plugin-ionic" in config.xml. Adding it to the project
[04:59:02]: ▸ Installing "cordova-plugin-ionic" for ios
[04:59:20]: ▸ Installing "cordova-plugin-add-swift-support" for ios


The installation of the plugin is vanilla, using FCM 
<platform name="ios">
  <resource-file src="GoogleService-Info.plist" />
</platform>

**Comment by smasherprog** [comment]
The fix for this was to use a different plugin 
https://github.com/fechanique/cordova-plugin-fcm
This works on ionics build servers and it simpler to use as well.. :(

**Comment by smasherprog** [comment]
macdonst  is it possible to include code from here https://github.com/fechanique/cordova-plugin-fcm
It doesnt look like that repo is being maintained, but the implementation doesnt require cocopods or any special setup...
