### ISSUE TITLE
Crash reported by Crashlytics

### ISSUE THREAD

**Issue by bushev** [phonegap/phonegap-plugin-push#2190]
### Expected Behaviour

No crash

### Actual Behaviour

Crash

### Reproduce Scenario (including but not limited to)

Not sure

#### Steps to Reproduce 

Not sure

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.0.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Batmobile > Defy Mini

#### Cordova CLI version and cordova platform version

cordova - 6.5.0
cordova-android - 6.4.0

#### Plugin version

phonegap-plugin-push - 2.1.2

#### Sample Push Data Payload

Not sure

#### Sample Code that illustrates the problem

Not sure

#### Logs taken while reproducing problem

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.adobe.phonegap.push.PushHandlerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.BaseBundle.getInt(java.lang.String, int)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by jcesarmobile** [comment]
Apparently the Batmobile is a fake device, so that crash report is not real, see https://stackoverflow.com/questions/46845607/is-batmobile-defy-mini-a-fake-device?noredirect=1&lq=1
