### ISSUE TITLE
Background push notifications throws exception in Android Oreo, sometimes leads to app crash

### ISSUE THREAD

**Issue by sreenivas1901** [phonegap/phonegap-plugin-push#2198]
### Expected Behaviour
Push notifications should be received by device when app is in foreground and background.

### Actual Behaviour
Push notifications are received and processed correctly when the app is in foreground. However when the app is in background, the data is received by the device, but an exception is thrown.

Notifications work correctly on previous version of android, and also on iOS. Issue only seen in Android O.

#### Steps to Reproduce 
- Create a hybrid mobile app
- Add Cordova, Android platform and phonegap-plugin-push
- Send notification via GCM.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
- FAIL: Android 8.0 - Oneplus 5T
- PASS: Android 7.x - Moto Z2 Play
- PASS: iOS 11.x - Apple iPhone 7

#### Cordova CLI version and cordova platform version

    cordova --version = 7.1.0
    cordova platform version android = 6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push = 1.8.4

#### Sample Push Data Payload
{
	"data": {
		"title": title,
		"body": body,
		"sound": "default",        
	},
	"custom_data_1": custom_data_1,
	"custom_data_2": custom_data_2
}

#### Logs taken while reproducing problem
02-09 12:10:00.173 28567-32066/com.oraclecorp.internal.ent2.RepConnect D/PushPlugin_GCMIntentService: onMessage - from: 70822285019
02-09 12:10:00.174 28567-32066/com.oraclecorp.internal.ent2.RepConnect D/PushPlugin_GCMIntentService: normalize extras
02-09 12:10:00.178 28567-32066/com.oraclecorp.internal.ent2.RepConnect D/PushPlugin_GCMIntentService: create notification
**02-09 12:10:00.178 28567-32066/com.oraclecorp.internal.ent2.RepConnect E/PushPlugin_GCMIntentService: Number format exception - Error parsing notId: s == null**
02-09 12:10:00.186 28567-32066/com.oraclecorp.internal.ent2.RepConnect D/PushPlugin_GCMIntentService: stored icon=null
02-09 12:10:00.187 28567-32066/com.oraclecorp.internal.ent2.RepConnect D/PushPlugin_GCMIntentService: stored iconColor=null
02-09 12:10:00.187 28567-32066/com.oraclecorp.internal.ent2.RepConnect D/PushPlugin_GCMIntentService: stored sound=true
02-09 12:10:00.187 28567-32066/com.oraclecorp.internal.ent2.RepConnect D/PushPlugin_GCMIntentService: stored vibrate=true
02-09 12:10:00.187 28567-32066/com.oraclecorp.internal.ent2.RepConnect D/PushPlugin_GCMIntentService: no icon resource found - using application icon
02-09 12:10:00.193 28567-32066/com.oraclecorp.internal.ent2.RepConnect D/PushPlugin_GCMIntentService: create actions: with in-line
02-09 12:10:00.193 28567-32066/com.oraclecorp.internal.ent2.RepConnect W/Notification: Use of stream types is deprecated for operations other than volume control
02-09 12:10:00.193 28567-32066/com.oraclecorp.internal.ent2.RepConnect W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case

#### Logs taken while reproducing problem (logs when the app crashes due to notification)
02-09 12:14:01.339 28567-28567/com.oraclecorp.internal.ent2.RepConnect E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: com.oraclecorp.internal.ent2.RepConnect, PID: 28567
                                                                                         **java.lang.RuntimeException: Unable to start receiver com.google.android.gms.gcm.GcmReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=com.oraclecorp.internal.ent2.RepConnect cmp=com.oraclecorp.internal.ent2.RepConnect/com.adobe.phonegap.push.GCMIntentService (has extras) }: app is in background uid UidRecord{13a6af2 u0a270 RCVR bg:+1m27s219ms idle procs:1 seq(0,0,0)}**
                                                                                             at android.app.ActivityThread.handleReceiver(ActivityThread.java:3424)
                                                                                             at android.app.ActivityThread.-wrap17(Unknown Source:0)
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1772)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                             at android.os.Looper.loop(Looper.java:164)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                          Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=com.oraclecorp.internal.ent2.RepConnect cmp=com.oraclecorp.internal.ent2.RepConnect/com.adobe.phonegap.push.GCMIntentService (has extras) }: app is in background uid UidRecord{13a6af2 u0a270 RCVR bg:+1m27s219ms idle procs:1 seq(0,0,0)}
                                                                                             at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1522)
                                                                                             at android.app.ContextImpl.startService(ContextImpl.java:1478)
                                                                                             at android.content.ContextWrapper.startService(ContextWrapper.java:645)
                                                                                             at android.content.ContextWrapper.startService(ContextWrapper.java:645)
                                                                                             at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:99)
                                                                                             at com.google.android.gms.gcm.GcmReceiver.doStartService(Unknown Source:22)
                                                                                             at com.google.android.gms.gcm.GcmReceiver.zzd(Unknown Source:0)
                                                                                             at com.google.android.gms.gcm.GcmReceiver.onReceive(Unknown Source:98)
                                                                                             at android.app.ActivityThread.handleReceiver(ActivityThread.java:3410)
                                                                                             at android.app.ActivityThread.-wrap17(Unknown Source:0) 
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1772) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                             at android.os.Looper.loop(Looper.java:164) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6809) 
                                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
02-09 12:14:01.342 28567-28567/com.oraclecorp.internal.ent2.RepConnect D/AppTracker: App Event: crash

**Comment by macdonst** [comment]
@sreenivas1901 yes, I'm pretty sure this is due to changes in the Android O and you will need to upgrade to the latest version of the push notification plugin which supports Android O and FCM. Google has changed background thread limitations in Android O.

Please upgrade the push plugin and confirm that it resolves your issue.

**Comment by Creawebs** [comment]
@macdonst I can confirm the same problem with latest version 
phonegap-plugin-push 2.1.3 "PushPlugin"
@ionic-native/push@4.5.3

Tested on Android O device

 @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.9.3
    npm               : 5.6.0
    OS                : Windows 10

Logcat:
02-09 20:26:12.849  4572  4572 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.IncompatibleClassChangeError: Superclass com.google.android.gms.internal.zzbej of com.google.firebase.messaging.RemoteMessage is declared final (declaration of 'com.google.firebase.messaging.RemoteMessage' appears in /data/app/io.ionic.starter-6sRYi3Y_743H1NUTW__38Q==/base.apk:classes2.dex)

Tested on a fresh new app.

**Comment by sreenivas1901** [comment]
I can confirm that I'm receiving the notifications in my Android O device after updating the plugin to v2.1.3. However, I would like to test older versions of Android and iOS devices as well, before providing final confirmation (will be able to test only on Monday).

**Comment by macdonst** [comment]
@Creawebs that's not the same problem. You can try updating Play Services on your device and if that is up to date take a look at #2129 as you may need to bump the gradle version until a new cordova-android get released.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
