### ISSUE TITLE
platform add iOS push error ON PROXY

### ISSUE THREAD

**Issue by bhumin3i** [phonegap/phonegap-plugin-push#2263]
I'm using proxy server and already set http_proxy but I think push plugin stop while 'clone master'

 

```
Installing "phonegap-plugin-push" for ios

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17/rbconfig.rb:214: warning: Insecure world writable dir /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/.bin in PATH, mode 040777

Failed to install 'phonegap-plugin-push': Error: pod: Command failed with exit code 1 Error output:
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17/rbconfig.rb:214: warning: Insecure world writable dir /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/.bin in PATH, mode 040777
    at ChildProcess.whenDone (/Users/bhumin/Desktop/gitREPO/rtidev/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

(node:12744) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: pod: Command failed with exit code 1 Error output:
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17/rbconfig.rb:214: warning: Insecure world writable dir /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/.bin in PATH, mode 040777
(node:12744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bhumin3i** [comment]
sorry for opening issue 
adding proxy setting in ~/.bash_profile file is solve my problem 

export http_proxy=http://xxx:xx
export https_proxy=http://xxx:xx
export ALL_PROXY=http://xxx:xx
