### ISSUE TITLE
Android crash on receiving notification

### ISSUE THREAD

**Issue by Spillo17** [phonegap/phonegap-plugin-push#2267]
### Expected Behaviour
On receiving a push notification tetx contained into it will be shown on the app

### Actual Behaviour
On receiving a push notification app crash

#### Platform and Version
   android version: 7.0

#### (Android) What device vendor 
   Honor 6x

#### Cordova CLI version and cordova platform version
   cordova version: 8.0.0                           
   platform android version: 7.1.0                

#### Plugin version
    phonegap-plugin-push 2.2.2 "PushPlugin"

#### Sample Push Data Payload

`{
    "notification": {
        "title": "News",
        "body": "Today weather!"
    },
    "data" : {
        "degrees": "12",
        "weather": "sunny",
    }
}
`

#### Logs taken while reproducing problem
```
03-16 10:40:32.085 25018-25018/com.sample.app I/HwSecImmHelper: mSecurityInputMethodService is null
03-16 10:40:42.924 25018-25018/com.sample.app I/chromium: [INFO:CONSOLE(14700)] "localstorage", source: file:///android_asset/www/assets/lib/angular/angular.js (14700)
03-16 10:40:42.956 25018-25018/com.sample.app I/HwSecImmHelper: mSecurityInputMethodService is null
03-16 10:40:44.594 25018-25018/com.sample.app I/chromium: [INFO:CONSOLE(14700)] "response", source: file:///android_asset/www/assets/lib/angular/angular.js (14700)
03-16 10:40:58.088 25018-25018/com.sample.app I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.IncompatibleClassChangeError: Superclass com.google.android.gms.internal.zzbej of com.google.firebase.messaging.RemoteMessage is declared final (declaration of 'com.google.firebase.messaging.RemoteMessage' appears in /data/app/com.sample.app-2/split_lib_dependencies_apk.apk)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3310)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1659)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at void android.os.Looper.loop() (Looper.java:156)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
03-16 10:40:58.088 25018-25018/com.sample.app I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.IncompatibleClassChangeError: Superclass com.google.android.gms.internal.zzbej of com.google.firebase.messaging.RemoteMessage is declared final (declaration of 'com.google.firebase.messaging.RemoteMessage' appears in /data/app/com.sample.app-2/split_lib_dependencies_apk.apk)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
03-16 10:40:58.088 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3310)
03-16 10:40:58.089 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
03-16 10:40:58.089 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1659)
03-16 10:40:58.089 25018-25018/com.sample.app I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
03-16 10:40:58.089 25018-25018/com.sample.app I/art:     at void android.os.Looper.loop() (Looper.java:156)
03-16 10:40:58.089 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
03-16 10:40:58.089 25018-25018/com.sample.app I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
03-16 10:40:58.089 25018-25018/com.sample.app I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
03-16 10:40:58.089 25018-25018/com.sample.app I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
03-16 10:40:58.091 25018-25018/com.sample.app I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.IncompatibleClassChangeError: Superclass com.google.android.gms.internal.zzbej of com.google.firebase.messaging.RemoteMessage is declared final (declaration of 'com.google.firebase.messaging.RemoteMessage' appears in /data/app/com.sample.app-2/split_lib_dependencies_apk.apk)
03-16 10:40:58.091 25018-25018/com.sample.app I/art:     at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
03-16 10:40:58.091 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3310)
03-16 10:40:58.091 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
03-16 10:40:58.091 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1659)
03-16 10:40:58.091 25018-25018/com.sample.app I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
03-16 10:40:58.091 25018-25018/com.sample.app I/art:     at void android.os.Looper.loop() (Looper.java:156)
03-16 10:40:58.091 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
03-16 10:40:58.091 25018-25018/com.sample.app I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
03-16 10:40:58.091 25018-25018/com.sample.app I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
03-16 10:40:58.091 25018-25018/com.sample.app I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
03-16 10:40:58.099 25018-25018/com.sample.app I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.IncompatibleClassChangeError: Superclass com.google.android.gms.internal.zzbej of com.google.firebase.messaging.RemoteMessage is declared final (declaration of 'com.google.firebase.messaging.RemoteMessage' appears in /data/app/com.sample.app-2/split_lib_dependencies_apk.apk)
03-16 10:40:58.099 25018-25018/com.sample.app I/art:     at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
03-16 10:40:58.099 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3310)
03-16 10:40:58.099 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
03-16 10:40:58.099 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1659)
03-16 10:40:58.099 25018-25018/com.sample.app I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
03-16 10:40:58.099 25018-25018/com.sample.app I/art:     at void android.os.Looper.loop() (Looper.java:156)
03-16 10:40:58.099 25018-25018/com.sample.app I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
03-16 10:40:58.099 25018-25018/com.sample.app I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
03-16 10:40:58.099 25018-25018/com.sample.app I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:942)
03-16 10:40:58.099 25018-25018/com.sample.app I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:832)
03-16 10:40:58.104 25018-25018/com.sample.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.sample.app, PID: 25018
                                                                   java.lang.NoSuchMethodError: No static method zzchl()Lcom/google/firebase/iid/zzaa; in class Lcom/google/firebase/iid/zzaa; or its super classes (declaration of 'com.google.firebase.iid.zzaa' appears in /data/app/com.sample.app-2/split_lib_dependencies_apk.apk)
                                                                       at com.google.firebase.messaging.FirebaseMessagingService.zzp(Unknown Source)
                                                                       at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3476)
                                                                       at android.app.ActivityThread.-wrap23(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1674)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                       at android.os.Looper.loop(Looper.java:156)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by jonatarussi** [comment]
I am having the same problem here

**Comment by djeanaraujo** [comment]
After a day of hard work, I have found out that it is a conflict of versions of libs. In { `platforms/android/project.properties` is inserted: 
...
`com.google.firebase:firebase-messaging:11.6.2`
...
So, apparently you should use the same version in the libs with preffix `com.google.android.gms`. 
For example: **com.google.android.gms:play-services-analytics:+** should be **com.google.android.gms:play-services-analytics:11.6.2**.
Resuming, every lib which start with `com.google.android.gms` should use `11.6.2` as version.
I hope have helped.

**Comment by macdonst** [comment]
Yeah, if multiple plugins are using play services you want to make sure all the versions are matching. In the push plugin I have preferences you can set in order to make it easier to match up play services versions. In you config.xml you should see something like:

```
    <plugin name="phonegap-plugin-push">
        <variable name="ANDROID_SUPPORT_V13_VERSION" value="27.+" />
        <variable name="FCM_VERSION" value="11.6.2" />
    </plugin>
```

So you can tailor the FCM_VERSION for your project. 

If other plugins are causing the conflict please let me know the github url of the project so I can send a pull request.

**Comment by Spillo17** [comment]
@djeanaraujo & @macdonst 

The problem as you said was on the gms version in the `platforms/android/project.properties`.

**My old config** 
```
cordova.system.library.1=com.google.android.gms:play-services-auth:**11.+**
cordova.system.library.2=com.google.android.gms:play-services-identity:**11.+**
```

**Fixed config**
```
cordova.system.library.1=com.google.android.gms:play-services-auth:**11.6.2**
cordova.system.library.2=com.google.android.gms:play-services-identity:**11.6.2**
```

Many thanks guy I fixed it.

**Comment by jonatarussi** [comment]
Thank you guys.

I fixed setting the same version in all itens in `platforms/android/project.properties` too.

`com.google.android.gms:play-services-maps:11.8.0
com.google.android.gms:play-services-location:11.8.0
com.google.firebase:firebase-messaging:11.8.0
`

**Comment by jonatarussi** [comment]
Thank you guys.

I fixed setting the same version in all itens in `platforms/android/project.properties` too.

`com.google.android.gms:play-services-maps:11.8.0` 
`com.google.android.gms:play-services-location:11.8.0` 
`com.google.firebase:firebase-messaging:11.8.0`
