### ISSUE TITLE
Getting NoClassDefFoundError on Push Notification initialization

### ISSUE THREAD

**Issue by mpadmaraj** [phonegap/phonegap-plugin-push#2399]
My app was working fine till yesterday. But since yesterday it is giving this error. I have made no change to push notification code. following is from config.xml:
``
    <plugin name="phonegap-plugin-push" spec="~1.10.5"> 
        <variable name="SENDER_ID" value="939405804300" />  
    </plugin>
``
I have tried with FCM_VERSION variable also but still get the below error.

### Expected Behaviour
App should register for push notificatios
### Actual Behaviour
Getting this error:

06-05 08:14:25.564: E/AndroidRuntime(12999): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzv;
06-05 08:14:25.564: E/AndroidRuntime(12999): 	at com.google.android.gms.iid.zzo.<init>(Unknown Source)
06-05 08:14:25.564: E/AndroidRuntime(12999): 	at com.google.android.gms.iid.zzo.<init>(Unknown Source)
06-05 08:14:25.564: E/AndroidRuntime(12999): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
06-05 08:14:25.564: E/AndroidRuntime(12999): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
06-05 08:14:25.564: E/AndroidRuntime(12999): 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
06-05 08:14:25.564: E/AndroidRuntime(12999): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-05 08:14:25.564: E/AndroidRuntime(12999): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-05 08:14:25.564: E/AndroidRuntime(12999): 	at java.lang.Thread.run(Thread.java:760)
06-05 08:14:25.564: E/AndroidRuntime(12999): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.util.zzv" on path: DexPathList[[zip file "/data/app/com.ionicframework.appmentpatient452982-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ionicframework.appmentpatient452982-1/lib/arm64, /data/app/com.ionicframework.appmentpatient452982-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
06-05 08:14:25.564: E/AndroidRuntime(12999): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-05 08:14:25.564: E/AndroidRuntime(12999): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
06-05 08:14:25.564: E/AndroidRuntime(12999): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-05 08:14:25.564: E/AndroidRuntime(12999): 	... 8 more

### Reproduce Scenario (including but not limited to)
I have following in package.json
``
  "phonegap-plugin-push": "~1.10.5",
``

#### Steps to Reproduce 
Build the ionic app and run it on android phone
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ANDROID 7
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
MI
#### Cordova CLI version and cordova platform version
cordova --version     7.0.0
cordova platform version android  
Installed platforms:
  android 6.2.3
  browser 4.1.0
Available platforms: 
  blackberry10 ~3.8.0 (deprecated)
  ios ~4.5.1
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0

#### Plugin version
cordova plugin version | grep phonegap-plugin-push  
phonegap-plugin-push 1.10.5 "PushPlugin"

**Comment by l1nknyto** [comment]
try to update google play service in Android SDK manager

**Comment by mpadmaraj** [comment]
updating google play service did not work. Do I need to install this cordova plugin? https://github.com/chemerisuk/cordova-support-google-services
Strange thing is it was working till yesterday.

**Comment by macdonst** [comment]
@mpadmaraj it's probably another plugin which is also using GCM or Play Services and it's causing a conflict. What does your `build.gradle` look like?

**Comment by mpadmaraj** [comment]
```gradle
apply plugin: 'com.android.application'

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }

    // Switch the Android Gradle plugin version requirement depending on the
    // installed version of Gradle. This dependency is documented at
    // http://tools.android.com/tech-docs/new-build-system/version-compatibility
    // and https://issues.apache.org/jira/browse/CB-8143
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
    }
}

// Allow plugins to declare Maven dependencies via build-extras.gradle.
allprojects {
    repositories {
        mavenCentral();
        jcenter()
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.14.1'
}

// Configuration properties. Set these via environment variables, build-extras.gradle, or gradle.properties.
// Refer to: http://www.gradle.org/docs/current/userguide/tutorial_this_and_that.html
ext {
    apply from: 'CordovaLib/cordova.gradle'
    // The value for android.compileSdkVersion.
    if (!project.hasProperty('cdvCompileSdkVersion')) {
        cdvCompileSdkVersion = null;
    }
    // The value for android.buildToolsVersion.
    if (!project.hasProperty('cdvBuildToolsVersion')) {
        cdvBuildToolsVersion = null;
    }
    // Sets the versionCode to the given value.
    if (!project.hasProperty('cdvVersionCode')) {
        cdvVersionCode = null
    }
    // Sets the minSdkVersion to the given value.
    if (!project.hasProperty('cdvMinSdkVersion')) {
        cdvMinSdkVersion = null
    }
    // Whether to build architecture-specific APKs.
    if (!project.hasProperty('cdvBuildMultipleApks')) {
        cdvBuildMultipleApks = null
    }
    // .properties files to use for release signing.
    if (!project.hasProperty('cdvReleaseSigningPropertiesFile')) {
        cdvReleaseSigningPropertiesFile = null
    }
    // .properties files to use for debug signing.
    if (!project.hasProperty('cdvDebugSigningPropertiesFile')) {
        cdvDebugSigningPropertiesFile = null
    }
    // Set by build.js script.
    if (!project.hasProperty('cdvBuildArch')) {
        cdvBuildArch = null
    }

    // Plugin gradle extensions can append to this to have code run at the end.
    cdvPluginPostBuildExtras = []
}

// PLUGIN GRADLE EXTENSIONS START
apply from: "com-sarriaroman-photoviewer/appmentpatient452982-photoviewer.gradle"
apply from: "phonegap-plugin-push/appmentpatient452982-push.gradle"
// PLUGIN GRADLE EXTENSIONS END

def hasBuildExtras = file('build-extras.gradle').exists()
if (hasBuildExtras) {
    apply from: 'build-extras.gradle'
}

// Set property defaults after extension .gradle files.
if (ext.cdvCompileSdkVersion == null) {
    ext.cdvCompileSdkVersion = privateHelpers.getProjectTarget()
}
if (ext.cdvBuildToolsVersion == null) {
    ext.cdvBuildToolsVersion = privateHelpers.findLatestInstalledBuildTools()
}
if (ext.cdvDebugSigningPropertiesFile == null && file('debug-signing.properties').exists()) {
    ext.cdvDebugSigningPropertiesFile = 'debug-signing.properties'
}
if (ext.cdvReleaseSigningPropertiesFile == null && file('release-signing.properties').exists()) {
    ext.cdvReleaseSigningPropertiesFile = 'release-signing.properties'
}

// Cast to appropriate types.
ext.cdvBuildMultipleApks = cdvBuildMultipleApks == null ? false : cdvBuildMultipleApks.toBoolean();
ext.cdvMinSdkVersion = cdvMinSdkVersion == null ? null : Integer.parseInt('' + cdvMinSdkVersion)
ext.cdvVersionCode = cdvVersionCode == null ? null : Integer.parseInt('' + cdvVersionCode)

def computeBuildTargetName(debugBuild) {
    def ret = 'assemble'
    if (cdvBuildMultipleApks && cdvBuildArch) {
        def arch = cdvBuildArch == 'arm' ? 'armv7' : cdvBuildArch
        ret += '' + arch.toUpperCase().charAt(0) + arch.substring(1);
    }
    return ret + (debugBuild ? 'Debug' : 'Release')
}

// Make cdvBuild a task that depends on the debug/arch-sepecific task.
task cdvBuildDebug
cdvBuildDebug.dependsOn {
    return computeBuildTargetName(true)
}

task cdvBuildRelease
cdvBuildRelease.dependsOn {
    return computeBuildTargetName(false)
}

task cdvPrintProps << {
    println('cdvCompileSdkVersion=' + cdvCompileSdkVersion)
    println('cdvBuildToolsVersion=' + cdvBuildToolsVersion)
    println('cdvVersionCode=' + cdvVersionCode)
    println('cdvMinSdkVersion=' + cdvMinSdkVersion)
    println('cdvBuildMultipleApks=' + cdvBuildMultipleApks)
    println('cdvReleaseSigningPropertiesFile=' + cdvReleaseSigningPropertiesFile)
    println('cdvDebugSigningPropertiesFile=' + cdvDebugSigningPropertiesFile)
    println('cdvBuildArch=' + cdvBuildArch)
    println('computedVersionCode=' + android.defaultConfig.versionCode)
    android.productFlavors.each { flavor ->
        println('computed' + flavor.name.capitalize() + 'VersionCode=' + flavor.versionCode)
    }
}

android {
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }

    defaultConfig {
        versionCode cdvVersionCode ?: new BigInteger("" + privateHelpers.extractIntFromManifest("versionCode"))
        applicationId privateHelpers.extractStringFromManifest("package")

        if (cdvMinSdkVersion != null) {
            minSdkVersion cdvMinSdkVersion
        }
    }

    lintOptions {
      abortOnError false;
    }

    compileSdkVersion cdvCompileSdkVersion
    buildToolsVersion cdvBuildToolsVersion

    if (Boolean.valueOf(cdvBuildMultipleApks)) {
        productFlavors {
            armv7 {
                versionCode defaultConfig.versionCode*10 + 2
                ndk {
                    abiFilters "armeabi-v7a", ""
                }
            }
            x86 {
                versionCode defaultConfig.versionCode*10 + 4
                ndk {
                    abiFilters "x86", ""
                }
            }
            all {
                ndk {
                    abiFilters "all", ""
                }
            }
        }
    }
    /*

    ELSE NOTHING! DON'T MESS WITH THE VERSION CODE IF YOU DON'T HAVE TO!

    else if (!cdvVersionCode) {
      def minSdkVersion = cdvMinSdkVersion ?: privateHelpers.extractIntFromManifest("minSdkVersion")
      // Vary versionCode by the two most common API levels:
      // 14 is ICS, which is the lowest API level for many apps.
      // 20 is Lollipop, which is the lowest API level for the updatable system webview.
      if (minSdkVersion >= 20) {
        defaultConfig.versionCode += 9
      } else if (minSdkVersion >= 14) {
        defaultConfig.versionCode += 8
      }
    }
    */

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_6
        targetCompatibility JavaVersion.VERSION_1_6
    }

    if (cdvReleaseSigningPropertiesFile) {
        signingConfigs {
            release {
                // These must be set or Gradle will complain (even if they are overridden).
                keyAlias = ""
                keyPassword = "__unset" // And these must be set to non-empty in order to have the signing step added to the task graph.
                storeFile = null
                storePassword = "__unset"
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
        addSigningProps(cdvReleaseSigningPropertiesFile, signingConfigs.release)
    }
    if (cdvDebugSigningPropertiesFile) {
        addSigningProps(cdvDebugSigningPropertiesFile, signingConfigs.debug)
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.android.support:support-v4:+"
    compile "com.google.android.gms:play-services-analytics:+"
    compile "com.android.support:support-v4:24.1.1+"
    compile "com.razorpay:checkout:1.4.1"
    compile "com.android.support:support-v4:25.+"
    compile "com.android.support:appcompat-v7:25.+"
    compile "com.android.support:support-v13:23+"
    compile "com.google.android.gms:play-services-gcm:11+"
    compile "me.leolin:ShortcutBadger:1.1.14@aar"
    // SUB-PROJECT DEPENDENCIES END
}

def promptForReleaseKeyPassword() {
    if (!cdvReleaseSigningPropertiesFile) {
        return;
    }
    if ('__unset'.equals(android.signingConfigs.release.storePassword)) {
        android.signingConfigs.release.storePassword = privateHelpers.promptForPassword('Enter key store password: ')
    }
    if ('__unset'.equals(android.signingConfigs.release.keyPassword)) {
        android.signingConfigs.release.keyPassword = privateHelpers.promptForPassword('Enter key password: ');
    }
}

gradle.taskGraph.whenReady { taskGraph ->
    taskGraph.getAllTasks().each() { task ->
        if (task.name == 'validateReleaseSigning' || task.name == 'validateSigningRelease') {
            promptForReleaseKeyPassword()
        }
    }
}

def addSigningProps(propsFilePath, signingConfig) {
    def propsFile = file(propsFilePath)
    def props = new Properties()
    propsFile.withReader { reader ->
        props.load(reader)
    }

    def storeFile = new File(props.get('key.store') ?: privateHelpers.ensureValueExists(propsFilePath, props, 'storeFile'))
    if (!storeFile.isAbsolute()) {
        storeFile = RelativePath.parse(true, storeFile.toString()).getFile(propsFile.getParentFile())
    }
    if (!storeFile.exists()) {
        throw new FileNotFoundException('Keystore file does not exist: ' + storeFile.getAbsolutePath())
    }
    signingConfig.keyAlias = props.get('key.alias') ?: privateHelpers.ensureValueExists(propsFilePath, props, 'keyAlias')
    signingConfig.keyPassword = props.get('keyPassword', props.get('key.alias.password', signingConfig.keyPassword))
    signingConfig.storeFile = storeFile
    signingConfig.storePassword = props.get('storePassword', props.get('key.store.password', signingConfig.storePassword))
    def storeType = props.get('storeType', props.get('key.store.type', ''))
    if (!storeType) {
        def filename = storeFile.getName().toLowerCase();
        if (filename.endsWith('.p12') || filename.endsWith('.pfx')) {
            storeType = 'pkcs12'
        } else {
            storeType = signingConfig.storeType // "jks"
        }
    }
    signingConfig.storeType = storeType
}

for (def func : cdvPluginPostBuildExtras) {
    func()
}

// This can be defined within build-extras.gradle as:
//     ext.postBuildExtras = { ... code here ... }
if (hasProperty('postBuildExtras')) {
    postBuildExtras()
}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.0'
            }
        }
    }
}
````

**Comment by macdonst** [comment]
@mpadmaraj yeah, so in your dependencies:

```
    compile "com.google.android.gms:play-services-analytics:+"
    compile "com.google.android.gms:play-services-gcm:11+"
```

you are picking up the latest of one and 11.x of another causing the issue. You want to set the analytics and push plugins to use the same version of the libraries.

**Comment by mpadmaraj** [comment]
Thanks a lot @macdonst!!! that worked!

**Comment by PaliwalSparsh** [comment]
@mpadmaraj @macdonst Thankyou very much you guys rock 😄 
```
    compile "com.google.android.gms:play-services-analytics:+"
    compile "com.google.android.gms:play-services-gcm:+"
```
doing this fixed it for me.
