### ISSUE TITLE
Migrating gcm v1.11. to fcm 2.2.3: Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.

### ISSUE THREAD

**Issue by fgagneten** [phonegap/phonegap-plugin-push#2455]
After upgrading my phonega-plugin-push, I faced several problems related to this library. Could it be possible that I have more than one library with package name com.google.android.gms?

### Expected Behaviour
After 

    ionic cordova build android

BUILD SUCCEED
### Actual Behaviour
After 

    ionic cordova build android

BUILD FAILED

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
cordova -v

    8.0.0

#### Cordova CLI version and cordova platform version
cordova platform version android

    android 7.1.0

#### Plugin version

    cordova-android-firebase-gradle-release 1.0.2 "cordova-android-firebase-gradle-release"
    cordova-plugin-accountkit 1.4.0 "Cordova AccountKit"
    cordova-plugin-appminimize 1.0 "AppMinimize"
    cordova-plugin-camera 4.0.3 "Camera"
    cordova-plugin-contacts 3.0.1 "Contacts"
    cordova-plugin-device 2.0.2 "Device"
    cordova-plugin-dialogs 2.0.1 "Notification"
    cordova-plugin-email-composer 0.8.15 "EmailComposer"
    cordova-plugin-file 6.0.1 "File"
    cordova-plugin-file-transfer 1.7.1 "File Transfer"
    cordova-plugin-filepath 1.0.2 "FilePath"
    cordova-plugin-geolocation 4.0.1 "Geolocation"
    cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
    cordova-plugin-market 1.2.0 "Market"
    cordova-plugin-media-capture 3.0.2 "Capture"
    cordova-plugin-nativestorage 2.3.1 "NativeStorage"
    cordova-plugin-network-information 2.0.1 "Network Information"
    cordova-plugin-sim 1.3.3 "SIM"
    cordova-plugin-splashscreen 5.0.2 "Splashscreen"
    cordova-plugin-statusbar 2.4.2 "StatusBar"
    cordova-plugin-transport-security 0.1.2 "App Transport Security"
    cordova-plugin-whitelist 1.3.3 "Whitelist"
    cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
    cordova-plugin-x-toast 2.6.2 "Toast"
    cordova-support-google-services 1.1.0 "cordova-support-google-services"
    cordova.plugins.diagnostic 4.0.8 "Diagnostic"
    es6-promise-plugin 4.2.2 "Promise"
    ionic-plugin-keyboard 2.2.1 "Keyboard"
    phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
    phonegap-plugin-multidex 1.0.0 "Multidex"
    phonegap-plugin-push 2.2.3 "PushPlugin"`

#### Logs taken while reproducing problem

    Exception in thread "main" java.lang.IllegalArgumentException

        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)

 > Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.
com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\21.jar --output ProjectPath\platforms\android\app\build\intermediates\transforms\desugar\debug\23.jar --input ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\38.jar --output ProjectPath\platforms\android\app\build\intermediates\transforms\desugar\debug\40.jar --input ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\20.jar --output ProjectPath\platforms\android\app\build\intermediates\transforms\desugar\debug\22.jar --input ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\32.jar --output ProjectPath\platforms\android\app\build\intermediates\transforms\desugar\debug\34.jar --input ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\33.jar --output ProjectPath\platforms\android\app\build\intermediates\transforms\desugar\debug\35.jar --input ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\35.jar --output ProjectPath\platforms\android\app\build\intermediates\transforms\desugar\debug\37.jar --input ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\11.jar --output ProjectPath\platforms\android\app\build\intermediates\transforms\desugar\debug\13.jar --input ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\1.jar --output ProjectPath\platforms\android\app\build\intermediates\transforms\desugar\debug\3.jar --input ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\27.jar --output ProjectPath\platforms\android\app\build\intermediates\transforms\desugar\debug\29.jar --input ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\12.jar --output ProjectPath\platforms\android\app\build\intermediates\transforms\desugar\debug\14.jar --input ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\8.jar --output ProjectPath\platforms\android\app\build\intermediates\transforms\desugar\debug\10.jar --classpath_entry ProjectPath\platforms\android\CordovaLib\build\intermediates\intermediate-jars\debug\classes.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\classes\debug --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\0.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\1.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\2.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\3.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\4.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\5.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\6.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\7.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\8.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\9.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\10.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\11.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\12.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\13.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\14.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\15.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\16.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\17.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\18.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\19.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\20.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\21.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\22.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\23.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\24.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\25.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\26.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\27.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\28.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\29.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\30.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\31.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\32.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\33.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\34.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\35.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\36.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\37.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\38.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\39.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\40.jar --classpath_entry ProjectPath\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\41.jar --bootclasspath_entry C:\Users\Faustino\AppData\Local\Android\sdk\platforms\android-27\android.jar --bootclasspath_entry C:\Users\Faustino\AppData\Local\Android\sdk\platforms\android-27\optional\org.apache.http.legacy.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_102\jre\lib\resources.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_102\jre\lib\rt.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_102\jre\lib\jsse.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_102\jre\lib\jce.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_102\jre\lib\charsets.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_102\jre\lib\jfr.jar --min_sdk_version 19 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}`

**Comment by macdonst** [comment]
@fgagneten the first thing I'd do is run `cordova clean android` to get rid of any leftover build artifacts. Then run your build again and let me know if you get the same or similar error.
