### ISSUE TITLE
Android 8.1 Crash

### ISSUE THREAD

**Issue by fperez-eypscap** [phonegap/phonegap-plugin-push#2500]
### Expected Behaviour
Application registers push plugin and can receive notifications

### Actual Behaviour
Application crashes

#### Steps to Reproduce 
Open app.
Call:
PushNotification.init({
  android: {}
});

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Xiaomi Mi A1

#### Cordova CLI version and cordova platform version

    cordova --version                                    8.0.0
    cordova platform version android           7.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.2.3
    <plugin name="phonegap-plugin-push" spec="^2.2.3">
        <variable name="ANDROID_SUPPORT_V13_VERSION" value="27.1.1" />
        <variable name="FCM_VERSION" value="17.1.0" />
    </plugin>

#### Logs taken while reproducing problem
 D/AndroidRuntime: Shutting down VM
 E/AndroidRuntime: FATAL EXCEPTION: main
                   android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 vis=PRIVATE)
                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
                       at android.os.Handler.dispatchMessage(Handler.java:106)
                       at android.os.Looper.loop(Looper.java:172)
                       at android.app.ActivityThread.main(ActivityThread.java:6590)
                       at java.lang.reflect.Method.invoke(Native Method)
                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Other Android versions and working properly. Great plugin by the way.
Could this be related to this?
https://stackoverflow.com/questions/47531742/startforeground-fail-after-upgrade-to-android-8-1
Thanks.

**Comment by jcesarmobile** [comment]
As creator you can also close it
