### ISSUE TITLE
Unable to get provider com.google.firebase.provider.FirebaseInitProvider

### ISSUE THREAD

**Issue by brunojs02** [phonegap/phonegap-plugin-push#2501]
### Expected Behaviour
Application registers push plugin and can receive notifications

### Actual Behaviour
Application crashes

#### Steps to Reproduce 
build android platform
open project on android studio
build, install e and run app in samsung device (when the app is launched, the PushNotification.init is executed, or was meant to be)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.2.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung

#### Cordova CLI version and cordova platform version

    cordova --version                                    8.0.0
    cordova platform version android           7.0.0 

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   2.2.3

#### Logs taken while reproducing problem
07-27 15:56:04.543 17020-17020/package.appname E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: /data/app/package.appname.apk
        at android.app.ActivityThread.installProvider(ActivityThread.java:4984)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4593)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4533)
        at android.app.ActivityThread.access$1400(ActivityThread.java:150)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5279)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: /data/app/package.appname.apk
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4969)

**Comment by macdonst** [comment]
@brunojs02 Firebase seems to be missing on the device. Can you try and update the Play Store/Play Services app on that device and see if that fixes it.

**Comment by brunojs02** [comment]
I discovered the problem.. For some reason, the phonegap-plugin-push 2.2.3 dont work with cordova-android v: 7.0.0, i update cordova-android and it's work. thanks anyway
