### ISSUE TITLE
iOS: Plugin installation fails when other plugin already uses Firebase

### ISSUE THREAD

**Issue by andreszs** [phonegap/phonegap-plugin-push#2502]
### Expected Behaviour
Install plugin without errors.

### Actual Behaviour
```
Using cordova-fetch for cordova-ios@~4.5.1
(...)
Installing "cordova-plugin-badge" for ios
Installing "cordova-plugin-camera" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-dialogs" for ios
Installing "cordova-plugin-firebase-authentication" for ios
Installing "cordova-plugin-inappbrowser" for ios
Installing "cordova-plugin-native-spinner" for ios
Installing "cordova-plugin-network-information" for ios
Installing "cordova-plugin-splashscreen" for ios
Installing "cordova-plugin-statusbar" for ios
Installing "cordova-plugin-tiles" for ios
Installing "cordova-plugin-vibration" for ios
Installing "cordova-plugin-whitelist" for ios
Installing "cordova-plugin-windows-manifest" for ios
Installing "cordova-promise-polyfill" for ios
Installing "cordova-sms-plugin" for ios
Installing "cordova-support-android-plugin" for ios
Installing "cordova-support-google-services" for ios
Installing "phonegap-plugin-multidex" for ios
Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/andres/Documents/Cordova/myapp/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:862:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
Error: pod: Command failed with exit code 1
```
### Reproduce Scenario (including but not limited to)
Create app, add plugin such as [cordova-plugin-firebase-authentication](https://github.com/chemerisuk/cordova-plugin-firebase-authentication), and try to add this plugin then.
#### Cordova CLI version and cordova platform version

    cordova 7.1.0
    cordova-ios 4.5.1

#### Plugin version

    2.2.3

**Comment by Tarekajaj** [comment]
No workaround for this issue?

**Comment by andreszs** [comment]
@Tarekajaj Yes there is, [check out this PR](https://github.com/phonegap/phonegap-plugin-push/pull/2503) with the proposed solution, and read my last post about how to update www and plugins.

Install errors are gone, but cordova build errors persist, however they are irrelevan because you build from Xcode.
