### ISSUE TITLE
java.lang.ArrayStoreException: org.json.JSONObject$1 cannot be stored in an array of type java.lang.String[]

### ISSUE THREAD

**Issue by zadoli** [phonegap/phonegap-plugin-push#2526]
### Actual Behaviour

Force close of the app

#### Platform and Version

Android 6.0.1

#### Android) What device vendor

Xiaomi Redmi Note 3

#### Cordova CLI version and cordova platform version

    cordova --version                                    6.5.0
    cordova platform version android                     6.5.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.10.5

#### Logs taken while reproducing problem
java.lang.ArrayStoreException: org.json.JSONObject$1 cannot be stored in an array of type java.lang.String[]
	at com.google.android.gms.gcm.zza.zzf(Unknown Source)
	at com.google.android.gms.gcm.zza.zzs(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.handleIntent(Unknown Source)
	at com.google.android.gms.iid.zzc.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by jcesarmobile** [comment]
Looks like a problem in GCM library, make sure you are using latest version.

Anyway, we are not updating 1.x.x version anymore, you should move to 2.x.x and FCM as Google is deprecating GCM and will stop working next year.
