### ISSUE TITLE
App rejection on android play store - advertising ID

### ISSUE THREAD

**Issue by pliablepixels** [phonegap/phonegap-plugin-push#2571]
(phone gap plugin version 2.1.3, platform Android)

Hi, my android app suddenly got rejected today (after several years on the store) with this:

![screen shot 2018-10-01 at 3 56 32 pm](https://user-images.githubusercontent.com/4116654/46312330-c07b4000-c592-11e8-97d0-cd236fd92bbc.png)

I was pretty sure I did nothing with the advertising ID. Upon further investigation, it looks like this plugin uses firebase SDK which in turn [seems to collect](https://support.google.com/firebase/answer/6318039?hl=en) that ID. I see the irony with Google kicking my app out because I used their library.

If you think appropriate, you may want to add a notice in your README.md encouraging uses to add a privacy policy to their store listing _and_ their app if they use this plugin. I think these conditions are being scrutinized more closely due to GDPR compliance.

**Comment by lamuertepeluda** [comment]
All of a sudden I'm facing the same issue. If you *don't* need the advertising ID (like me: I didn't even know what it was), then you _may disable it_.

It would be nice to have an option that does that for both platforms (iOS and Android). I will arrange some hook-based solution for now, and I will share it here if it works, but an option in the cordova manifest preferences for this plugin would be nice.

References on disabling the Android ID: 
* https://github.com/arnesson/cordova-plugin-firebase/issues/862
* https://firebase.google.com/support/guides/disable-analytics

**Comment by jcesarmobile** [comment]
I would vote for documenting how to disable it by adding this line to the AndroidManifest.xml with a `edit-config` tag `<meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />`, as making the plugin disable it by default might cause problems with other plugins requiring it to properly work.

**Comment by drago-aca** [comment]
please let us know if it works..

**Comment by pliablepixels** [comment]
Thanks @lamuertepeluda. My app got put back the moment I [linked a privacy policy](https://medium.com/zmninja/zmninja-privacy-and-your-data-5489a5974baf) with a lame comment about firebase collecting IDs. That being said, I'll incorporate your changes. I don't do anything with the ad id and Apple's policies are are even stricter. You can't collect the ad id if you don't do anything with it (per my reading some time ago).

**Comment by lamuertepeluda** [comment]
@pliablepixels we neither... we got knowledge of the existence of this Advertising ID the moment our app was rejected! 😞 I hope this works... stay tuned

**Comment by lamuertepeluda** [comment]
Guys the edit-config approach did work for Google. I re-submitted our app and after 1h or so it was back in the play store. I hope they won't rejected it again.

I'll let you know if it works for iOS as well, but thanks @pliablepixels for your investigation!

**Comment by mrhyper** [comment]
>         <config-file parent="/manifest/application" target="AndroidManifest.xml">
>             <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />
>             <meta-data android:name="firebase_crash_collection_enabled" android:value="false" />
>         </config-file>
> ```
> 
> in the app `config.xml` file.

I can't compile my app with those settings, I get this error:
Error parsing XML: unbound prefix

**Comment by GabrielArakaki** [comment]
@mrhyper , don't have much information of your environment settings, but if you're working on cordova-android 7.x.x., the relative path to AndroidManifest.xml has changed.

So you should change the target in the config-file, such as:
```
<config-file parent="/manifest/application" target="app/src/main/AndroidManifest.xml">
        <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />
        <meta-data android:name="firebase_crash_collection_enabled" android:value="false" />
</config-file>
```

@see
https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

**Comment by Charlie-Hua** [comment]
@mrhyper adding an attribute to the root `<widget>` works for me.
from this comment: https://github.com/dpa99c/cordova-custom-config/issues/24#issuecomment-172981002

**Comment by touletan** [comment]
I added this code below to config.xml and successfully build the APK using phonegap build. I submitted the apps on Google and it has been active for few hours. Not the apps has been removed again for the same reason :) Is it still working for you?

`<config-file parent="/manifest/application" target="app/src/main/AndroidManifest.xml">
        <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />
        <meta-data android:name="firebase_crash_collection_enabled" android:value="false" />
</config-file>`

**Comment by jdtaylor91** [comment]
@touletan we also added the same snippet to our config.xml and the app was removed for the same reason a few hours later. Did you find another work around for this?

We confirmed that the generated AndroidManifest.xml file contains both the `google_analytics_adid_collection_enabled` and `firebase_crash_collection_enabled` settings so we don't think it's a configuration issue.

**Comment by touletan** [comment]
@jdtaylor91 ,  I added a privacy policy to my app.

**Comment by jdtaylor91** [comment]
@touletan OK thanks. We've had to go down this route as well unfortunately!

**Comment by digaus** [comment]
Is it enough to upload the modified version and release it? Cause it is still removed and I do not see any updates even 5 hours after submitting

**Comment by digaus** [comment]
```
2019-05-29 05:26:06.316 4947-4947/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.home.shelly, PID: 4947
    java.lang.RuntimeException: Unable to instantiate application com.home.shelly.firebase_crash_collection_enabled: java.lang.ClassNotFoundException: Didn't find class "com.home.shelly.firebase_crash_collection_enabled" on path: DexPathList[[zip file "/data/app/com.home.shelly-tFJdYmN_zRmCq2tIygploQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.home.shelly-tFJdYmN_zRmCq2tIygploQ==/lib/arm64, /data/app/com.home.shelly-tFJdYmN_zRmCq2tIygploQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1164)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6529)
        at android.app.ActivityThread.access$1900(ActivityThread.java:267)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.home.shelly.firebase_crash_collection_enabled" on path: DexPathList[[zip file "/data/app/com.home.shelly-tFJdYmN_zRmCq2tIygploQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.home.shelly-tFJdYmN_zRmCq2tIygploQ==/lib/arm64, /data/app/com.home.shelly-tFJdYmN_zRmCq2tIygploQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1127)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1156)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6529) 
        at android.app.ActivityThread.access$1900(ActivityThread.java:267) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7470) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 

```

Hmm getting this error on startup

**Comment by digaus** [comment]
> @mrhyper , don't have much information of your environment settings, but if you're working on cordova-android 7.x.x., the relative path to AndroidManifest.xml has changed.
> 
> So you should change the target in the config-file, such as:
> 
> ```
> <config-file parent="/manifest/application" target="app/src/main/AndroidManifest.xml">
>         <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />
>         <meta-data android:name="firebase_crash_collection_enabled" android:value="false" />
> </config-file>
> ```
> 
> @see
> https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

Ty this worked perfectly. My last release is now active since ~5 days!

**Comment by tmladek** [comment]
> I added this code below to config.xml and successfully build the APK using phonegap build. I submitted the apps on Google and it has been active for few hours. Not the apps has been removed again for the same reason :) Is it still working for you?
> 
> `<config-file parent="/manifest/application" target="app/src/main/AndroidManifest.xml"> <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" /> <meta-data android:name="firebase_crash_collection_enabled" android:value="false" /> </config-file>`

I added this into my `config.xml`, but then my handler stopped getting called?

Registration and getting the ID worked fine, but no notification would ever trigger the "notifications" event again. I had to remove this from the config, completely delete all artifacts and cache and rebuild to fix this - which obviously isn't ideal, as now my app is getting rejected again.

Any news regarding this issue?
