### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/internal/FirebaseInstanceIdInternal;

### ISSUE THREAD

**Issue by atulkrajput** [phonegap/phonegap-plugin-push#2631]
App crashing on start with following error on logcat :

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/internal/FirebaseInstanceIdInternal;
        at com.google.firebase.iid.Registrar.getComponents(Unknown Source:30)
        at com.google.firebase.components.zzg.<init>(Unknown Source:33)
        at com.google.firebase.FirebaseApp.<init>(Unknown Source:114)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:108)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:3)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:32)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source:4)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:26)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6285)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

#### Cordova CLI version and cordova platform version

    8.1.2 (cordova-lib@8.1.1)
    android 7.1.2

#### Plugin version
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 3.1.0 "Facebook Connect"
cordova-plugin-googleplus-fix 5.3.3 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-otp-auto-verification 1.0.1 "OTPAutoVerification"
cordova-plugin-qrscanner 2.6.0 "QRScanner"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-shortcuts-android 0.1.0 "Android Shortcuts"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"

#### Android Studio project properties
target=android-27
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.facebook.android:facebook-android-sdk:4.37.0
cordova.system.library.2=com.google.android.gms:play-services-auth:16.0.1
cordova.system.library.3=com.google.android.gms:play-services-identity:16.0.0
cordova.gradle.include.1=cordova-plugin-qrscanner/cmd-qrscanner.gradle
cordova.system.library.4=com.android.support:support-compat:27.0.0
cordova.gradle.include.2=cordova-support-google-services/cmd-build.gradle
cordova.gradle.include.3=phonegap-plugin-multidex/cmd-multidex.gradle
cordova.system.library.5=com.android.support:support-v13:27.+
cordova.system.library.6=me.leolin:ShortcutBadger:1.1.17@aar
cordova.system.library.7=com.google.firebase:firebase-messaging:15.0.2
cordova.system.library.8=com.google.android.gms:play-services-location:16.0.0

#### Sample Code that illustrates the problem
Problem started as i added location plugin "cordova-plugin-request-location-accuracy "

Can anyone please guide which version of "play-services-location" i have to use with "firebase-messaging:15.0.2"

**Comment by atulkrajput** [comment]
Problem solved after upgrading to android 7.1.4
