### ISSUE TITLE
Phonegap Build fails with 2.x for Android

### ISSUE THREAD

**Issue by jomorr2** [phonegap/phonegap-plugin-push#2792]
### Expected Behaviour
Phonegap Builds succeed using CLI 7.1.0 and 2.x

### Actual Behaviour
Starting after July 8th, builds with any 2.x version fail when building using Phonegap Build

### Reproduce Scenario (including but not limited to)
A package using CLI 7.1.0 and phonegap-plugin-push version 2.1.0 worked with no issue on July 8th, 2019.  Using the same package with Phonegap Build on July 14th fails for Android, but succeeds for iOS.

#### Steps to Reproduce 
including these lines in the config.xml

<preference name='phonegap-version' value='cli-7.1.0' />
<engine name="android" spec="^6.3.0" />
<plugin name="phonegap-plugin-push" spec="2.1.2">

#### Cordova CLI version and cordova platform version
cli 7.1.0

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version
2.1.2

#### Logs taken while reproducing problem

:transformClassesWithJarMergingForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v13/view/DragStartHelper$OnDragStartListener.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.114 secs
Error: /var/gimlet/tmp/47183924979800/3283330/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v13/view/DragStartHelper$OnDragStartListener.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/var/gimlet/tmp/47183924979800/3283330/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by jomorr2** [comment]
Upgrading to plugin version 2.2.1 resolved the issue.

**Comment by jomorr2** [comment]
I am reopening since updating to 2.2.1 did allow the build to complete, but the PGB Cordova CLI version isn't compatible so the plugin was skipped.  I have tried plugin version 2.1.2, 2.1.0 and 2.0.0 all with the same results.  As mentioned in the initial report, builds worked fine with plugin version 2.1.2 and cli 7.1.0 prior to July 8th.
