### ISSUE TITLE
iOS Build fails in Phonegap build cli-9.0.0

### ISSUE THREAD

**Issue by phiasco12** [phonegap/phonegap-plugin-push#2798]
### Expected Behaviour

install the plugin 

### Actual Behaviour

plugin installation fails in iOS.

### Reproduce Scenario (including but not limited to)

Try to install the plugin via phonegap build

#### Steps to Reproduce 

Add this to your config.xml file of your phonegap project:

```
<preference name="phonegap-version" value='cli-9.0.0' />
<plugin name="phonegap-plugin-push" source="npm" />
```

and try to build your app via Phonegap build.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS, phonegap build

#### Cordova CLI version and cordova platform version

PhoneGap (iOS / Android / Windows)
cli-9.0.0 (5.0.1 / 8.0.0 / 7.0.0)

#### Plugin version

    Latest version via:

`<plugin name="phonegap-plugin-push" source="npm" />`

#### Logs taken while reproducing problem

I get the following error under iOS section of phonegap build.

`Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "phonegap-plugin-push" via npm Installing "phonegap-plugin-push" at "2.2.3" for ios "framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag. Running command: pod install --verbose Failed to install 'phonegap-plugin-push': Error: pod: Command failed with exit code 1 at ChildProcess.whenDone (/private/tmp/gimlet/XXXXXXXX/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23) at ChildProcess.emit (events.js:182:13) at maybeClose (internal/child_process.js:962:16) at Socket.stream.socket.on (internal/child_process.js:381:11) at Socket.emit (events.js:182:13) at Pipe._handle.close (net.js:611:12) pod: Command failed with exit code 1 - You can fix this`

**Comment by Ferdzzzzzzzz** [comment]
Same error, I tested moving back down to ios 4.5.5 and it worked again, I read something about plugin push using a firebase tool that's out of date? Can't find the post again though, will try to find it and repost here.

**Comment by paymanzafar** [comment]
Same error. Even with Phonegap cli-8.1.1 & 8.0.0 & 7.1.0
with cli-7.0.1 builds without error, but does not work.

**Comment by jomorr2** [comment]
I am having the same problem.  I can't get a build to succeed using this plugin so I am moving to a different plugin.

**Comment by phiasco12** [comment]
> Same error. Even with Phonegap cli-8.1.1 & 8.0.0 & 7.1.0
> with cli-7.0.1 builds without error, but does not work.

Works fine with cli-8.1.1

**Comment by phiasco12** [comment]
> I am having the same problem. I can't get a build to succeed using this plugin so I am moving to a different plugin.

this plugin has many conflicting issues with other plugins. so you issue might be other plugins that you use not this plugin.

**Comment by phiasco12** [comment]
Today, I managed to build successfully with cli-9.0.0 and this plugin. so i reckon the developers have done some changes. Thanks boys and gals...

**Comment by Ferdzzzzzzzz** [comment]
Any more news on this? I'm still getting the same error, now managing about 25 apps with Android sitting on Cordova 9 and iOS on Cordova 8, it's getting a bit messy 😢   Android has to be on Cordova 9 for Android 28 support. Any help would be very very much appreciated 😄

**Comment by jomorr2** [comment]
> Any more news on this? I'm still getting the same error, now managing about 25 apps with Android sitting on Cordova 9 and iOS on Cordova 8, it's getting a bit messy 😢   Android has to be on Cordova 9 for Android 28 support. Any help would be very very much appreciated 😄

Have you tried to build recently?  Builds started working again for me a few weeks ago with no changes on my side.  I don't know what was changed, or where, but I am glad it is working again.

**Comment by alsocalledchris** [comment]
Also having issues with this...

**Comment by Perh0rd** [comment]
Same here.

**Comment by piyushmanurkar** [comment]
Any update for this issue?
