### ISSUE TITLE
Fresh Ionic project fails to build with this plugin

### ISSUE THREAD

**Issue by joshstrange** [phonegap/phonegap-plugin-push#2809]
### Expected Behaviour
Project can build after adding this plugin (no code using the plugin yet)

### Actual Behaviour
Cannot build app

````
...
[cordova] ** ARCHIVE FAILED **
[cordova]
[cordova]
[cordova] The following build commands failed:
[cordova] 	CompileC /Users/josh/Library/Developer/Xcode/DerivedData/Check-In-aldchlxvikokzpfoovtloprdyosi/Build/Intermediates.noindex/ArchiveIntermediates/Check-In/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/Protobuf.build/Objects-normal/arm64/Wrappers.pbobjc.o /Users/josh/git/mobile/check-in/current-new3/platforms/ios/Pods/Protobuf/objectivec/google/protobuf/Wrappers.pbobjc.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[cordova] 	CompileC /Users/josh/Library/Developer/Xcode/DerivedData/Check-In-aldchlxvikokzpfoovtloprdyosi/Build/Intermediates.noindex/ArchiveIntermediates/Check-In/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/Protobuf.build/Objects-normal/arm64/Type.pbobjc.o /Users/josh/git/mobile/check-in/current-new3/platforms/ios/Pods/Protobuf/objectivec/google/protobuf/Type.pbobjc.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[cordova] 	CompileC /Users/josh/Library/Developer/Xcode/DerivedData/Check-In-aldchlxvikokzpfoovtloprdyosi/Build/Intermediates.noindex/ArchiveIntermediates/Check-In/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/Protobuf.build/Objects-normal/arm64/Struct.pbobjc.o /Users/josh/git/mobile/check-in/current-new3/platforms/ios/Pods/Protobuf/objectivec/google/protobuf/Struct.pbobjc.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[cordova] (3 failures)
[cordova] Command finished with error code 65: xcodebuild -workspace,Check-In.xcworkspace,-scheme,Check-In,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,Check-In.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/josh/git/mobile/check-in/current-new3/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/josh/git/mobile/check-in/current-new3/platforms/ios/build/sharedpch,GCC_PREPROCESSOR_DEFINITIONS='DEBUG=1',-UseModernBuildSystem=1
[cordova] Error: xcodebuild: Command failed with exit code 65
[cordova]     at ChildProcess.whenDone (/Users/josh/git/mobile/check-in/current-new3/node_modules/cordova-common/src/superspawn.js:135:23)
[cordova]     at ChildProcess.emit (events.js:198:13)
[cordova]     at maybeClose (internal/child_process.js:982:16)
[cordova]     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[cordova] xcodebuild: Command failed with exit code 65
````

### Reproduce Scenario (including but not limited to)

Running Ionic project

#### Steps to Reproduce 

* Create new Ionic 4 project `ionic start test tabs`
* Change app identifier
* Add iOS `ionic cordova platforms add ios@5.0.1`
* Add plugin `ionic cordova plugins add phonegap-plugin-push@2.2.3`
* Run project `ionic cordova run ios --device -l --consolelogs`

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 12.1

#### Cordova CLI version and cordova platform version
````
8.1.2 (cordova-lib@8.1.1)

Installed platforms:
  ios 5.0.1
Available platforms:
  android ~7.1.1
  browser ~5.0.1
  osx ~4.0.1
  windows ~6.0.0
````
#### Plugin version
    2.2.3

#### Sample Push Data Payload

N/A

#### Sample Code that illustrates the problem

N/A

#### Logs taken while reproducing problem

(see above)

**Comment by ucsbricks** [comment]
Any news on this issue yet? I got the same error.

9.0.0 (cordova-lib@9.0.1)

Installed platforms:
  android 8.0.0
  ios 5.0.1

Plugin version
  2.2.3

**Comment by richardshergold** [comment]
I'm having the same issue - have you got anywhere?  My issue only occurs when I set the target to iOS 10 i.e it builds ok if I set it to iOS 11.

See separate issue [here ](https://github.com/phonegap/phonegap-plugin-push/issues/2794)

**Comment by richardshergold** [comment]
By the the way, I also found that stepping down from iOS 5.0.1 to 4.5.5 solves the issue but I don't really want to do that as the app I am talking about is being migrated from Ionic 3 to Ionic 4 and in the Ionic 3 version everything works fine at iOS 5.0.0.

**Comment by ucsbricks** [comment]
I can confirm building works for target iOS 11 w/

9.0.0 (cordova-lib@9.0.1)

Installed platforms:
android 8.1.0
ios 5.0.1

Plugin version
2.3.0

**Comment by Finesse** [comment]
I solved the problem by downgrading the Cordova iOS version from 5.1.1. to 4.5.5. The app works fine after the downgrade.
