### ISSUE TITLE
[Android] Crashlytics report - NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String, int)' on a null object reference

### ISSUE THREAD

**Issue by 8bhsolutions** [phonegap/phonegap-plugin-push#2903]
### Expected Behaviour
No exception thrown

### Actual Behaviour
NullPointerException

### Reproduce Scenario (including but not limited to)
Not sure

#### Steps to Reproduce 
Not sure

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.1.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LGE Nexus 5X

#### Cordova CLI version and cordova platform version
cordova: 9.0.0 (cordova-lib@9.0.1)
cordova-android: 8.1.0

#### Plugin version
phonegap-plugin-push: 2.3.0

#### Sample Push Data Payload
Not sure

#### Sample Code that illustrates the problem
Not sure

#### Logs taken while reproducing problem

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eightbhs.personal_safety/com.adobe.phonegap.push.PushHandlerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String, int)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String, int)' on a null object reference
       at com.adobe.phonegap.push.PushHandlerActivity.onCreate(PushHandlerActivity.java:28)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by 8bhsolutions** [comment]
**Context**
The time of the Crashlytics report is before the app_start event.
So it would seem that the use start app, and this crash occurs straight away.

**Additional Info**
I've reviewed the Java code w.r.t PushHandlerActivity.onCreate, and was unable to determine how this case is even possible.
PushHandlerActivity is created in 4 places (via Intent), and each instance has the Extras populated.

I would appreciate anyone who might have some ideas/suggestion on how this scenario can be reproduced.
