### ISSUE TITLE
App crashes after adding push plugin and wikipedia app installed

### ISSUE THREAD

**Issue by souly1** [phonegap/phonegap-plugin-push#357]
Hi,
I've been having a weird issue with my app ever since I've added this plugin: a new exception appears, but only if wikipedia app is installed on device (Exception attached below).
Any idea as to where to start in solving this, aside to asking my users to not install wikipedia app :P

java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=file:///android_asset/www/undefined cmp=org.wikipedia/.settings.LicenseActivity } from ProcessRecord{1ad050bc 32296:com.xx.doubleX/u0a454} (pid=32296, uid=10454) not exported from uid 10211
	at android.os.Parcel.readException(Parcel.java:1546)
	at android.os.Parcel.readException(Parcel.java:1499)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2714)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1510)
	at android.app.Activity.startActivityForResult(Activity.java:4076)
	at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:337)
	at android.app.Activity.startActivityForResult(Activity.java:4023)
	at android.app.Activity.startActivity(Activity.java:4347)
	at android.app.Activity.startActivity(Activity.java:4315)
	at org.apache.cordova.inappbrowser.InAppBrowser.openExternal(InAppBrowser.java:346)
	at org.apache.cordova.inappbrowser.InAppBrowser$1.run(InAppBrowser.java:176)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6891)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by souly1** [comment]
OK, sorry for wasting your time. 
Good news (or bad news, depends on how you look at it), the issue was with cordova-admob-pro plugin (forgot I uninstalled and reinstalled it which probably bumped up the version), once removed looks ok, I'll refer my issue to @floatinghotpot
