### ISSUE TITLE
Can't install multiple versions of app that has the plugin [Android]

### ISSUE THREAD

**Issue by eladmoshe** [phonegap/phonegap-plugin-push#474]
When I try to install multiple versions of of the an app (dev, test..., each with different bundle name) the second installation fails with an error (see below).
When I remove the plugin from the app it works fine. 
```
W/PackageManager(  936): com.android.server.pm.PackageManagerException: Can't install because provider name com.google.android.gms.measurement.google_measurement_service (in package com.XXXXX.qaBeta) is already used by com.XXXXX.dev
W/PackageManager(  936): 	at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:7140)
W/PackageManager(  936): 	at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:6771)
W/PackageManager(  936): 	at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:12847)
W/PackageManager(  936): 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:13721)
W/PackageManager(  936): 	at com.android.server.pm.PackageManagerService.access$2600(PackageManagerService.java:319)
W/PackageManager(  936): 	at com.android.server.pm.PackageManagerService$7.run(PackageManagerService.java:11040)
W/PackageManager(  936): 	at android.os.Handler.handleCallback(Handler.java:739)
W/PackageManager(  936): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/PackageManager(  936): 	at android.os.Looper.loop(Looper.java:145)
W/PackageManager(  936): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/PackageManager(  936): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by macdonst** [comment]
@eladmoshe what version of the plugin are you using as this should not be an issue in the latest plugin.

**Comment by eladmoshe** [comment]
@macdonst I upgraded to 1.5.2, still happening. I would very appreciate any clue to what might cause the issue.

**Comment by eladmoshe** [comment]
Indeed fixed by upgrading to the latest version. For reference this is the relevant commit:  https://github.com/phonegap/phonegap-plugin-push/commit/15b76632ac2849f1cb2f48e75a5292dfaa97de7f.

Thanks!
