### ISSUE TITLE
android  runing Exception

### ISSUE THREAD

**Issue by gitHubLie** [phonegap/phonegap-plugin-push#496]
java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE

**Comment by gitHubLie** [comment]
who is know this exception?

**Comment by gitHubLie** [comment]
01-13 17:58:08.040: E/AndroidRuntime(12030): java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1712)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at android.app.ContextImpl.startService(ContextImpl.java:1689)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at android.content.ContextWrapper.startService(ContextWrapper.java:515)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at com.google.android.gms.iid.zzc.zzb(Unknown Source)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at com.google.android.gms.iid.zzc.zza(Unknown Source)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at com.google.android.gms.iid.zzc.zzb(Unknown Source)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at com.google.android.gms.iid.zzc.zza(Unknown Source)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-13 17:58:08.040: E/AndroidRuntime(12030): 	at java.lang.Thread.run(Thread.java:818)

**Comment by macdonst** [comment]
@gitHubLie how are you getting this error? The plugin.xml will add that permission into your app for you.

**Comment by macdonst** [comment]
@gitHubLie I'm closing this due to inactivity. The only thing I can think of is you need to make sure that:

```
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
```

gets added to your AndroidManifest.xml, which it should automatically.
