### ISSUE TITLE
1.6.x branch fails on build

### ISSUE THREAD

**Issue by sanmed** [phonegap/phonegap-plugin-push#589]
I pulled in the 1.6.x branch as I really needed interactive push actions to work with the app in the background.

I get the following error when the app is built:

`
```
	android Build Tooling revision 2016.01.27.2r
	Warning: Failed to install 'phonegap-plugin-push':Error: Variable(s) missing: SENDER_ID
    at /home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/cordova-lib/cordova-lib/src/plugman/install.js:324:23
    at _fulfilled (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:749:13)
    at /home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:557:44
    at flush (/home/builder/BpcTooling/Cordova3/node_modules/plugman/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
	Warning: Variable(s) missing: SENDER_ID
	Warning: /home/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:189
							throw Error("exit code: " + code);
							^

Error: exit code: 1
    at Error (native)
    at ChildProcess.<anonymous> (/home/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:189:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	Error: Build failed during execution
	Error: 'Build failed with error code 1

```

**Comment by macdonst** [comment]
@sanmed right, when you add the plugin to the config.xml you'll need to add the SENDER_ID variable. If you don't use GCM then just make something up.

https://github.com/phonegap/phonegap-plugin-push/commit/0b8fd63345b863ec1d69b3ee22a5fdb469b7bbb2
