### ISSUE TITLE
DexException, Can not cordova compile

### ISSUE THREAD

**Issue by jwall149** [phonegap/phonegap-plugin-push#893]
### Expected Behaviour
cordova should be able to compile

### Actual Behaviour
cordova compile fails with exception

### Reproduce Scenario (including but not limited to)
Default webapp for meteor + pushPlugin
List of plugins:
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-meteor-webapp 1.3.0 "Meteor Webapp"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.0.2 "Cordova WKWebView Engine"
phonegap-plugin-push 1.6.3 "PushPlugin"

#### Steps to Reproduce 
cordova compile

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
HTC

#### Cordova CLI version and cordova platform version

cordova -v
6.0.0
cordova platform version android 
Installed platforms: android 5.1.1

#### Plugin version

    1.6.3

#### Logs taken while reproducing problem

gradle dependencies:

+--- com.android.support:support-v13:23+ -> 23.1.1
|    \--- com.android.support:support-v4:23.1.1
|         \--- com.android.support:support-annotations:23.1.1
+--- com.google.android.gms:play-services-gcm:+ -> 8.4.0
|    +--- com.google.android.gms:play-services-base:8.4.0
|    |    \--- com.google.android.gms:play-services-basement:8.4.0
|    |         \--- com.android.support:support-v4:23.0.0 -> 23.1.1 (*)
|    \--- com.google.android.gms:play-services-measurement:8.4.0
|         \--- com.google.android.gms:play-services-basement:8.4.0 (*)
\--- project :CordovaLib

UNEXPECTED TOP-LEVEL EXCEPTION:

com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ItemListIntents;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

**Comment by jwall149** [comment]
phonegap-plugin-push doesn't have any problem, but meteor 1.3 does, wrong place to put this. I will close this. Sorry.
